export const IRREGULAR_VERBS = [
  // A
  { inf: 'arise',   v2: 'arose',      v3: 'arisen',      hy: 'առաջանալ',        ru: 'возникать' },
  { inf: 'awake',   v2: 'awoke',      v3: 'awoken',      hy: 'արթնանալ',        ru: 'просыпаться' },
  // B
  { inf: 'be',      v2: 'was / were', v3: 'been',        hy: 'լինել',           ru: 'быть' },
  { inf: 'beat',    v2: 'beat',       v3: 'beaten',      hy: 'հարվածել',        ru: 'бить' },
  { inf: 'become',  v2: 'became',     v3: 'become',      hy: 'դառնալ',          ru: 'становиться' },
  { inf: 'begin',   v2: 'began',      v3: 'begun',       hy: 'սկսել',           ru: 'начинать' },
  { inf: 'bend',    v2: 'bent',       v3: 'bent',        hy: 'ծռել',            ru: 'сгибать' },
  { inf: 'bite',    v2: 'bit',        v3: 'bitten',      hy: 'կծել',            ru: 'кусать' },
  { inf: 'blow',    v2: 'blew',       v3: 'blown',       hy: 'փչել',            ru: 'дуть' },
  { inf: 'break',   v2: 'broke',      v3: 'broken',      hy: 'կոտրել',          ru: 'ломать' },
  { inf: 'bring',   v2: 'brought',    v3: 'brought',     hy: 'բերել',           ru: 'приносить' },
  { inf: 'build',   v2: 'built',      v3: 'built',       hy: 'կառուցել',        ru: 'строить' },
  { inf: 'burn',    v2: 'burnt / burned', v3: 'burnt / burned', hy: 'այրել',    ru: 'гореть' },
  { inf: 'buy',     v2: 'bought',     v3: 'bought',      hy: 'գնել',            ru: 'покупать' },
  // C
  { inf: 'catch',   v2: 'caught',     v3: 'caught',      hy: 'բռնել',           ru: 'ловить' },
  { inf: 'choose',  v2: 'chose',      v3: 'chosen',      hy: 'ընտրել',          ru: 'выбирать' },
  { inf: 'come',    v2: 'came',       v3: 'come',        hy: 'գալ',             ru: 'приходить' },
  { inf: 'cost',    v2: 'cost',       v3: 'cost',        hy: 'արժել',           ru: 'стоить' },
  { inf: 'cut',     v2: 'cut',        v3: 'cut',         hy: 'կտրել',           ru: 'резать' },
  // D
  { inf: 'deal',    v2: 'dealt',      v3: 'dealt',       hy: 'վերաբերվել',      ru: 'иметь дело' },
  { inf: 'dig',     v2: 'dug',        v3: 'dug',         hy: 'փորել',           ru: 'копать' },
  { inf: 'do',      v2: 'did',        v3: 'done',        hy: 'անել',            ru: 'делать' },
  { inf: 'draw',    v2: 'drew',       v3: 'drawn',       hy: 'նկարել',          ru: 'рисовать' },
  { inf: 'drink',   v2: 'drank',      v3: 'drunk',       hy: 'խմել',            ru: 'пить' },
  { inf: 'drive',   v2: 'drove',      v3: 'driven',      hy: 'վարել',           ru: 'водить' },
  // E
  { inf: 'eat',     v2: 'ate',        v3: 'eaten',       hy: 'ուտել',           ru: 'есть' },
  // F
  { inf: 'fall',    v2: 'fell',       v3: 'fallen',      hy: 'ընկնել',          ru: 'падать' },
  { inf: 'feel',    v2: 'felt',       v3: 'felt',        hy: 'զգալ',            ru: 'чувствовать' },
  { inf: 'fight',   v2: 'fought',     v3: 'fought',      hy: 'կռվել',           ru: 'бороться' },
  { inf: 'find',    v2: 'found',      v3: 'found',       hy: 'գտնել',           ru: 'находить' },
  { inf: 'fly',     v2: 'flew',       v3: 'flown',       hy: 'թռչել',           ru: 'летать' },
  { inf: 'forget',  v2: 'forgot',     v3: 'forgotten',   hy: 'մոռանալ',         ru: 'забывать' },
  { inf: 'forgive', v2: 'forgave',    v3: 'forgiven',    hy: 'ների',            ru: 'прощать' },
  { inf: 'freeze',  v2: 'froze',      v3: 'frozen',      hy: 'սառեցնել',        ru: 'замерзать' },
  // G
  { inf: 'get',     v2: 'got',        v3: 'got / gotten', hy: 'ստանալ',         ru: 'получать' },
  { inf: 'give',    v2: 'gave',       v3: 'given',       hy: 'տալ',             ru: 'давать' },
  { inf: 'go',      v2: 'went',       v3: 'gone',        hy: 'գնալ',            ru: 'идти' },
  { inf: 'grow',    v2: 'grew',       v3: 'grown',       hy: 'աճել',            ru: 'расти' },
  // H
  { inf: 'hang',    v2: 'hung',       v3: 'hung',        hy: 'կախել',           ru: 'вешать' },
  { inf: 'have',    v2: 'had',        v3: 'had',         hy: 'ունենալ',         ru: 'иметь' },
  { inf: 'hear',    v2: 'heard',      v3: 'heard',       hy: 'լսել',            ru: 'слышать' },
  { inf: 'hide',    v2: 'hid',        v3: 'hidden',      hy: 'թաքնվել',         ru: 'прятать' },
  { inf: 'hit',     v2: 'hit',        v3: 'hit',         hy: 'հարվածել',        ru: 'ударять' },
  { inf: 'hold',    v2: 'held',       v3: 'held',        hy: 'բռնել',           ru: 'держать' },
  { inf: 'hurt',    v2: 'hurt',       v3: 'hurt',        hy: 'ցավ պատճառել',    ru: 'причинять боль' },
  // K
  { inf: 'keep',    v2: 'kept',       v3: 'kept',        hy: 'պահել',           ru: 'держать' },
  { inf: 'kneel',   v2: 'knelt',      v3: 'knelt',       hy: 'ծնկաչոք կանգնել', ru: 'стоять на коленях' },
  { inf: 'know',    v2: 'knew',       v3: 'known',       hy: 'իմանալ',          ru: 'знать' },
  // L
  { inf: 'lay',     v2: 'laid',       v3: 'laid',        hy: 'դնել',            ru: 'класть' },
  { inf: 'lead',    v2: 'led',        v3: 'led',         hy: 'առաջնորդել',      ru: 'вести' },
  { inf: 'learn',   v2: 'learnt / learned', v3: 'learnt / learned', hy: 'սովորել', ru: 'учиться' },
  { inf: 'leave',   v2: 'left',       v3: 'left',        hy: 'հեռանալ',         ru: 'уходить' },
  { inf: 'lend',    v2: 'lent',       v3: 'lent',        hy: 'փոխ տալ',         ru: 'одалживать' },
  { inf: 'let',     v2: 'let',        v3: 'let',         hy: 'թույլ տալ',       ru: 'позволять' },
  { inf: 'lie',     v2: 'lay',        v3: 'lain',        hy: 'պառկել',          ru: 'лежать' },
  { inf: 'lose',    v2: 'lost',       v3: 'lost',        hy: 'կորցնել',         ru: 'терять' },
  // M
  { inf: 'make',    v2: 'made',       v3: 'made',        hy: 'պատրաստել',       ru: 'делать' },
  { inf: 'mean',    v2: 'meant',      v3: 'meant',       hy: 'նշանակել',        ru: 'означать' },
  { inf: 'meet',    v2: 'met',        v3: 'met',         hy: 'հանդիպել',        ru: 'встречать' },
  // P
  { inf: 'pay',     v2: 'paid',       v3: 'paid',        hy: 'վճարել',          ru: 'платить' },
  { inf: 'put',     v2: 'put',        v3: 'put',         hy: 'դնել',            ru: 'класть' },
  // R
  { inf: 'read',    v2: 'read',       v3: 'read',        hy: 'կարդալ',          ru: 'читать' },
  { inf: 'ride',    v2: 'rode',       v3: 'ridden',      hy: 'հեծնել',          ru: 'ехать' },
  { inf: 'ring',    v2: 'rang',       v3: 'rung',        hy: 'զանգել',          ru: 'звонить' },
  { inf: 'rise',    v2: 'rose',       v3: 'risen',       hy: 'բարձրանալ',       ru: 'подниматься' },
  { inf: 'run',     v2: 'ran',        v3: 'run',         hy: 'վազել',           ru: 'бегать' },
  // S
  { inf: 'say',     v2: 'said',       v3: 'said',        hy: 'ասել',            ru: 'говорить' },
  { inf: 'see',     v2: 'saw',        v3: 'seen',        hy: 'տեսնել',          ru: 'видеть' },
  { inf: 'sell',    v2: 'sold',       v3: 'sold',        hy: 'վաճառել',         ru: 'продавать' },
  { inf: 'send',    v2: 'sent',       v3: 'sent',        hy: 'ուղարկել',        ru: 'отправлять' },
  { inf: 'set',     v2: 'set',        v3: 'set',         hy: 'դնել / տեղադրել', ru: 'ставить' },
  { inf: 'shake',   v2: 'shook',      v3: 'shaken',      hy: 'ցնցել',           ru: 'трясти' },
  { inf: 'shoot',   v2: 'shot',       v3: 'shot',        hy: 'կրակել',          ru: 'стрелять' },
  { inf: 'show',    v2: 'showed',     v3: 'shown',       hy: 'ցույց տալ',       ru: 'показывать' },
  { inf: 'shut',    v2: 'shut',       v3: 'shut',        hy: 'փակել',           ru: 'закрывать' },
  { inf: 'sing',    v2: 'sang',       v3: 'sung',        hy: 'երգել',           ru: 'петь' },
  { inf: 'sink',    v2: 'sank',       v3: 'sunk',        hy: 'խորտակվել',       ru: 'тонуть' },
  { inf: 'sit',     v2: 'sat',        v3: 'sat',         hy: 'նստել',           ru: 'сидеть' },
  { inf: 'sleep',   v2: 'slept',      v3: 'slept',       hy: 'քնել',            ru: 'спать' },
  { inf: 'speak',   v2: 'spoke',      v3: 'spoken',      hy: 'խոսել',           ru: 'говорить' },
  { inf: 'spend',   v2: 'spent',      v3: 'spent',       hy: 'ծախսել',          ru: 'тратить' },
  { inf: 'split',   v2: 'split',      v3: 'split',       hy: 'պառակտել',        ru: 'разделять' },
  { inf: 'spread',  v2: 'spread',     v3: 'spread',      hy: 'տարածել',         ru: 'распространять' },
  { inf: 'stand',   v2: 'stood',      v3: 'stood',       hy: 'կանգնել',         ru: 'стоять' },
  { inf: 'steal',   v2: 'stole',      v3: 'stolen',      hy: 'գողանալ',         ru: 'красть' },
  { inf: 'stick',   v2: 'stuck',      v3: 'stuck',       hy: 'կպցնել',          ru: 'прилипать' },
  { inf: 'sting',   v2: 'stung',      v3: 'stung',       hy: 'խայթել',          ru: 'жалить' },
  { inf: 'strike',  v2: 'struck',     v3: 'struck',      hy: 'հարվածել',        ru: 'ударять' },
  { inf: 'swear',   v2: 'swore',      v3: 'sworn',       hy: 'երդվել',          ru: 'клясться' },
  { inf: 'sweep',   v2: 'swept',      v3: 'swept',       hy: 'ավլել',           ru: 'подметать' },
  { inf: 'swim',    v2: 'swam',       v3: 'swum',        hy: 'լողալ',           ru: 'плавать' },
  { inf: 'swing',   v2: 'swung',      v3: 'swung',       hy: 'ճոճել',           ru: 'качать' },
  // T
  { inf: 'take',    v2: 'took',       v3: 'taken',       hy: 'վերցնել',         ru: 'брать' },
  { inf: 'teach',   v2: 'taught',     v3: 'taught',      hy: 'սովորեցնել',      ru: 'учить' },
  { inf: 'tear',    v2: 'tore',       v3: 'torn',        hy: 'պոկել',           ru: 'рвать' },
  { inf: 'tell',    v2: 'told',       v3: 'told',        hy: 'ասել',            ru: 'рассказывать' },
  { inf: 'think',   v2: 'thought',    v3: 'thought',     hy: 'մտածել',          ru: 'думать' },
  { inf: 'throw',   v2: 'threw',      v3: 'thrown',      hy: 'նետել',           ru: 'бросать' },
  // U
  { inf: 'understand', v2: 'understood', v3: 'understood', hy: 'հասկանալ',     ru: 'понимать' },
  // W
  { inf: 'wake',    v2: 'woke',       v3: 'woken',       hy: 'արթնանալ',        ru: 'просыпаться' },
  { inf: 'wear',    v2: 'wore',       v3: 'worn',        hy: 'հագնել',          ru: 'носить' },
  { inf: 'win',     v2: 'won',        v3: 'won',         hy: 'հաղթել',          ru: 'побеждать' },
  { inf: 'write',   v2: 'wrote',      v3: 'written',     hy: 'գրել',            ru: 'писать' },
];
