export const DATA = [
  // ═══════════ A-LEVEL PHRASAL ═══════════

  // PUT
  {
    lv: 'A',
    cat: 'object',
    type: 'phrasal',
    base: 'put',
    tr: '/pʊt/',
    ru: 'класть / ставить',
    hy: 'դնել / դնել',
    forms: [
      {
        w: 'put on',
        tr: '/pʊt ɒn/',
        ru: 'надевать',
        hy: 'հագնել',
        ex: "Put on your jacket, it's cold outside.",
      },
      {
        w: 'put off',
        tr: '/pʊt ɒf/',
        ru: 'откладывать',
        hy: 'հետաձգել',
        ex: "Don't put off your homework until tomorrow.",
      },
      {
        w: 'put down',
        tr: '/pʊt daʊn/',
        ru: 'положить вниз / унижать',
        hy: 'դնել ներքև / նսեմացնել',
        ex: 'Put down your phone and listen.',
      },
      {
        w: 'put up',
        tr: '/pʊt ʌp/',
        ru: 'повесить / поднять',
        hy: 'կախել / բարձրացնել',
        ex: 'They put up new posters on the wall.',
      },
      {
        w: 'put out',
        tr: '/pʊt aʊt/',
        ru: 'потушить / выставить',
        hy: 'մարել / դնել դրսում',
        ex: 'Put out the candles before you sleep.',
      },
      {
        w: 'put through',
        tr: '/pʊt θruː/',
        ru: 'соединить по телефону',
        hy: 'կապել հեռախոսով',
        ex: 'Please put me through to the manager.',
      },
    ],
  },

  // GET
  {
    lv: 'A',
    cat: 'motion',
    type: 'phrasal',
    base: 'get',
    tr: '/ɡet/',
    ru: 'получать / становиться',
    hy: 'ստանալ / դառնալ',
    forms: [
      {
        w: 'get up',
        tr: '/ɡet ʌp/',
        ru: 'вставать',
        hy: 'վեր կենալ',
        ex: 'I get up at 6 every morning.',
      },
      {
        w: 'get in',
        tr: '/ɡet ɪn/',
        ru: 'войти / сесть в машину',
        hy: 'մտնել / նստել մեքենա',
        ex: "Get in the car, we're late!",
      },
      {
        w: 'get out',
        tr: '/ɡet aʊt/',
        ru: 'выйти',
        hy: 'դուրս գալ',
        ex: "Get out of the water, it's dangerous.",
      },
      {
        w: 'get on',
        tr: '/ɡet ɒn/',
        ru: 'садиться (автобус)',
        hy: 'նստել (ավտոբուս)',
        ex: 'Get on the bus at stop number 5.',
      },
      {
        w: 'get off',
        tr: '/ɡet ɒf/',
        ru: 'выходить (транспорт)',
        hy: 'իջնել (տրանսպորտ)',
        ex: 'We get off at the next station.',
      },
      {
        w: 'get back',
        tr: '/ɡet bæk/',
        ru: 'вернуться',
        hy: 'վերադառնալ',
        ex: 'When do you get back from London?',
      },
      {
        w: 'get over',
        tr: '/ɡet ˈəʊvə/',
        ru: 'оправиться / пережить',
        hy: 'հաղթահարել',
        ex: 'It took months to get over the breakup.',
      },
      {
        w: 'get along',
        tr: '/ɡet əˈlɒŋ/',
        ru: 'ладить с кем-то',
        hy: 'լավ հարաբերություններ ունենալ',
        ex: 'Do you get along with your colleagues?',
      },
    ],
  },

  // GO
  {
    lv: 'A',
    cat: 'motion',
    type: 'phrasal',
    base: 'go',
    tr: '/ɡəʊ/',
    ru: 'идти / ехать',
    hy: 'գնալ',
    forms: [
      {
        w: 'go on',
        tr: '/ɡəʊ ɒn/',
        ru: 'продолжать',
        hy: 'շարունակել',
        ex: "Go on, I'm listening to every word.",
      },
      {
        w: 'go out',
        tr: '/ɡəʊ aʊt/',
        ru: 'выходить / встречаться',
        hy: 'դուրս գնալ',
        ex: 'Do you want to go out for dinner?',
      },
      {
        w: 'go back',
        tr: '/ɡəʊ bæk/',
        ru: 'возвращаться',
        hy: 'վերադառնալ',
        ex: 'I want to go back to my home city.',
      },
      {
        w: 'go away',
        tr: '/ɡəʊ əˈweɪ/',
        ru: 'уйти / уехать',
        hy: 'հեռանալ',
        ex: 'Go away, I need some quiet time.',
      },
      {
        w: 'go through',
        tr: '/ɡəʊ θruː/',
        ru: 'пережить / просмотреть',
        hy: 'անցնել / վերանայել',
        ex: 'Go through your notes before the exam.',
      },
      {
        w: 'go along',
        tr: '/ɡəʊ əˈlɒŋ/',
        ru: 'соглашаться / идти вместе',
        hy: 'համաձայնել',
        ex: "I'll go along with whatever you decide.",
      },
    ],
  },

  // COME
  {
    lv: 'A',
    cat: 'motion',
    type: 'phrasal',
    base: 'come',
    tr: '/kʌm/',
    ru: 'приходить',
    hy: 'գալ',
    forms: [
      {
        w: 'come in',
        tr: '/kʌm ɪn/',
        ru: 'войти',
        hy: 'մտնել',
        ex: 'Come in, the door is open for you.',
      },
      {
        w: 'come back',
        tr: '/kʌm bæk/',
        ru: 'вернуться',
        hy: 'վերադառնալ',
        ex: 'Come back soon, we miss you already.',
      },
      {
        w: 'come on',
        tr: '/kʌm ɒn/',
        ru: 'давай / поторопись',
        hy: 'արի / շտապիր',
        ex: "Come on, we're going to be late!",
      },
      {
        w: 'come up',
        tr: '/kʌm ʌp/',
        ru: 'подойти / возникнуть',
        hy: 'մոտենալ / ծագել',
        ex: 'An unexpected problem came up at work.',
      },
      {
        w: 'come across',
        tr: '/kʌm əˈkrɒs/',
        ru: 'наткнуться на',
        hy: 'հանդիպել (պատահաբար)',
        ex: 'I came across a great article online.',
      },
      {
        w: 'come down',
        tr: '/kʌm daʊn/',
        ru: 'снизиться / спуститься',
        hy: 'իջնել / նվազել',
        ex: 'Prices finally came down this month.',
      },
    ],
  },

  // RUN
  {
    lv: 'A',
    cat: 'motion',
    type: 'phrasal',
    base: 'run',
    tr: '/rʌn/',
    ru: 'бежать / работать',
    hy: 'վազել',
    forms: [
      {
        w: 'run out',
        tr: '/rʌn aʊt/',
        ru: 'закончиться',
        hy: 'վերջանալ',
        ex: 'We ran out of coffee again.',
      },
      {
        w: 'run away',
        tr: '/rʌn əˈweɪ/',
        ru: 'убежать',
        hy: 'փախչել',
        ex: 'He ran away from his problems instead of solving them.',
      },
      {
        w: 'run into',
        tr: '/rʌn ˈɪntə/',
        ru: 'случайно встретить',
        hy: 'պատահաբար հանդիպել',
        ex: 'I ran into my old teacher at the market.',
      },
      {
        w: 'run over',
        tr: '/rʌn ˈəʊvə/',
        ru: 'сбить машиной',
        hy: 'վրաերթի  ենթարկել',
        ex: 'Be careful crossing — someone was run over here.',
      },
    ],
  },

  // TAKE
  {
    lv: 'A',
    cat: 'object',
    type: 'phrasal',
    base: 'take',
    tr: '/teɪk/',
    ru: 'брать',
    hy: 'վերցնել',
    forms: [
      {
        w: 'take off',
        tr: '/teɪk ɒf/',
        ru: 'снять / взлетать',
        hy: 'հանել / թռչել',
        ex: 'Take off your shoes at the door.',
      },
      {
        w: 'take on',
        tr: '/teɪk ɒn/',
        ru: 'взять на себя',
        hy: 'ստանձնել',
        ex: 'I took on too many tasks this week.',
      },
      {
        w: 'take out',
        tr: '/teɪk aʊt/',
        ru: 'вынуть / пойти куда-то',
        hy: 'հանել / դուրս տանել',
        ex: 'Take out the trash before you go.',
      },
      {
        w: 'take over',
        tr: '/teɪk ˈəʊvə/',
        ru: 'взять под контроль',
        hy: 'ստանձնել հսկողությունը',
        ex: 'She took over the project completely.',
      },
      {
        w: 'take up',
        tr: '/teɪk ʌp/',
        ru: 'заняться / занимать место',
        hy: 'զբաղվել / զբաղեցնել',
        ex: 'I took up swimming last summer.',
      },
      {
        w: 'take back',
        tr: '/teɪk bæk/',
        ru: 'взять назад / забрать',
        hy: 'հետ վերցնել',
        ex: 'Can I take back what I said?',
      },
    ],
  },

  // GIVE
  {
    lv: 'A',
    cat: 'people',
    type: 'phrasal',
    base: 'give',
    tr: '/ɡɪv/',
    ru: 'давать / отдавать',
    hy: 'տալ',
    forms: [
      {
        w: 'give up',
        tr: '/ɡɪv ʌp/',
        ru: 'сдаться',
        hy: 'հանձնվել',
        ex: 'Never give up on your dreams.',
      },
      {
        w: 'give out',
        tr: '/ɡɪv aʊt/',
        ru: 'раздать / иссякнуть',
        hy: 'բաժանել / սպառել',
        ex: 'Give out the worksheets to everyone.',
      },
      {
        w: 'give back',
        tr: '/ɡɪv bæk/',
        ru: 'вернуть',
        hy: 'վերադարձնել',
        ex: 'Give back my book when you finish.',
      },
      {
        w: 'give in',
        tr: '/ɡɪv ɪn/',
        ru: 'уступить / сдаться',
        hy: 'ենթարկվել',
        ex: 'After hours of arguing he finally gave in.',
      },
      {
        w: 'give away',
        tr: '/ɡɪv əˈweɪ/',
        ru: 'раздать / выдать секрет',
        hy: 'բաժանել անվճար / բացել գաղտնիք',
        ex: "Don't give away the ending of the film!",
      },
    ],
  },

  // BREAK
  {
    lv: 'A',
    cat: 'object',
    type: 'phrasal',
    base: 'break',
    tr: '/breɪk/',
    ru: 'ломать',
    hy: 'կոտրել',
    forms: [
      {
        w: 'break up',
        tr: '/breɪk ʌp/',
        ru: 'расстаться / разбиться',
        hy: 'բաժանվել',
        ex: 'They broke up after three years together.',
      },
      {
        w: 'break down',
        tr: '/breɪk daʊn/',
        ru: 'сломаться / расплакаться',
        hy: 'կոտրվել / արտասվել',
        ex: 'My laptop broke down right before the deadline.',
      },
      {
        w: 'break in',
        tr: '/breɪk ɪn/',
        ru: 'взломать / прервать',
        hy: 'ներխուժել',
        ex: 'Someone broke into our car last night.',
      },
      {
        w: 'break out',
        tr: '/breɪk aʊt/',
        ru: 'вырваться / вспыхнуть',
        hy: 'բռնկվել',
        ex: 'A fire broke out in the factory.',
      },
      {
        w: 'break off',
        tr: '/breɪk ɒf/',
        ru: 'оборвать / отломить',
        hy: 'կտրել / ընդհատել',
        ex: 'She broke off the engagement suddenly.',
      },
    ],
  },

  // TURN
  {
    lv: 'A',
    cat: 'daily',
    type: 'phrasal',
    base: 'turn',
    tr: '/tɜːn/',
    ru: 'поворачивать / включать',
    hy: 'շրջել / միացնել',
    forms: [
      {
        w: 'turn on',
        tr: '/tɜːn ɒn/',
        ru: 'включить',
        hy: 'միացնել',
        ex: "Turn on the lights, it's getting dark.",
      },
      {
        w: 'turn off',
        tr: '/tɜːn ɒf/',
        ru: 'выключить',
        hy: 'անջատել',
        ex: 'Turn off your phone during the meeting.',
      },
      {
        w: 'turn up',
        tr: '/tɜːn ʌp/',
        ru: 'прибавить / появиться',
        hy: 'բարձրացնել / հայտնվել',
        ex: 'Turn up the music, I love this song!',
      },
      {
        w: 'turn down',
        tr: '/tɜːn daʊn/',
        ru: 'убавить / отказать',
        hy: 'ցածրացնել / մերժել',
        ex: 'He turned down the job offer.',
      },
      {
        w: 'turn around',
        tr: '/tɜːn əˈraʊnd/',
        ru: 'повернуться / улучшиться',
        hy: 'շրջվել / բարելավվել',
        ex: 'The company turned around after new management.',
      },
    ],
  },

  // LOOK
  {
    lv: 'A',
    cat: 'people',
    type: 'phrasal',
    base: 'look',
    tr: '/lʊk/',
    ru: 'смотреть',
    hy: 'նայել',
    forms: [
      {
        w: 'look for',
        tr: '/lʊk fɔː/',
        ru: 'искать',
        hy: 'փնտրել',
        ex: "I'm looking for a good English course.",
      },
      {
        w: 'look after',
        tr: '/lʊk ˈɑːftə/',
        ru: 'присматривать',
        hy: 'հոգ տանել',
        ex: 'Can you look after my cat this weekend?',
      },
      {
        w: 'look up',
        tr: '/lʊk ʌp/',
        ru: 'найти информацию',
        hy: 'փնտրել (բառ/տեղեկություն)',
        ex: 'Look up the word in a dictionary.',
      },
      {
        w: 'look down on',
        tr: '/lʊk daʊn ɒn/',
        ru: 'смотреть свысока',
        hy: 'արհամարհել',
        ex: 'Never look down on people who know less.',
      },
      {
        w: 'look forward to',
        tr: '/lʊk ˈfɔːwəd tə/',
        ru: 'с нетерпением ждать',
        hy: 'անհամբեր սպասել',
        ex: 'I look forward to meeting you in person.',
      },
      {
        w: 'look into',
        tr: '/lʊk ˈɪntə/',
        ru: 'расследовать / изучить',
        hy: 'հետաքննել',
        ex: 'The police are looking into the case.',
      },
    ],
  },

  // MAKE
  {
    lv: 'A',
    cat: 'people',
    type: 'phrasal',
    base: 'make',
    tr: '/meɪk/',
    ru: 'делать / создавать',
    hy: 'անել / պատրաստել',
    forms: [
      {
        w: 'make up',
        tr: '/meɪk ʌp/',
        ru: 'помириться / придумать',
        hy: 'հաշտվել / հնարել',
        ex: 'They argued but made up the next morning.',
      },
      {
        w: 'make out',
        tr: '/meɪk aʊt/',
        ru: 'разобрать / целоваться',
        hy: 'հասկանալ / համբուրվել',
        ex: "I can't make out what the sign says.",
      },
      {
        w: 'make up for',
        tr: '/meɪk ʌp fɔː/',
        ru: 'компенсировать',
        hy: 'փոխհատուցել',
        ex: "I'll make up for missing your birthday.",
      },
      {
        w: 'make fun of',
        tr: '/meɪk fʌn ɒv/',
        ru: 'смеяться над',
        hy: 'ծաղրել',
        ex: "It's unkind to make fun of others.",
      },
    ],
  },

  // KEEP
  {
    lv: 'A',
    cat: 'daily',
    type: 'phrasal',
    base: 'keep',
    tr: '/kiːp/',
    ru: 'держать / продолжать',
    hy: 'պահել / շարունակել',
    forms: [
      {
        w: 'keep on',
        tr: '/kiːp ɒn/',
        ru: 'продолжать',
        hy: 'շարունակել',
        ex: "Keep on studying even when it's hard.",
      },
      {
        w: 'keep up',
        tr: '/kiːp ʌp/',
        ru: 'не отставать',
        hy: 'հետ չմնալ',
        ex: 'Keep up the good work!',
      },
      {
        w: 'keep in touch',
        tr: '/kiːp ɪn tʌtʃ/',
        ru: 'оставаться на связи',
        hy: 'կապի մեջ մնալ',
        ex: "Let's keep in touch after the trip.",
      },
      {
        w: 'keep away',
        tr: '/kiːp əˈweɪ/',
        ru: 'держаться подальше',
        hy: 'հեռու մնալ',
        ex: 'Keep away from negative people.',
      },
      {
        w: 'keep up with',
        tr: '/kiːp ʌp wɪð/',
        ru: 'не отставать от',
        hy: 'հետ չմնալ (ինչ-որ բանից)',
        ex: "I can't keep up with all the new words.",
      },
    ],
  },

  // HANG
  {
    lv: 'A',
    cat: 'daily',
    type: 'phrasal',
    base: 'hang',
    tr: '/hæŋ/',
    ru: 'вешать / зависать',
    hy: 'կախել / ժամանակ անցկացնել',
    forms: [
      {
        w: 'hang on',
        tr: '/hæŋ ɒn/',
        ru: 'подожди',
        hy: 'սպասիր',
        ex: "Hang on, I'll be with you in a minute.",
      },
      {
        w: 'hang out',
        tr: '/hæŋ aʊt/',
        ru: 'тусоваться',
        hy: 'ժամանակ անցկացնել',
        ex: "Let's hang out this weekend.",
      },
      {
        w: 'hang up',
        tr: '/hæŋ ʌp/',
        ru: 'повесить трубку',
        hy: 'հեռախոսը կտրել',
        ex: 'She hung up without saying goodbye.',
      },
      {
        w: 'hang around',
        tr: '/hæŋ əˈraʊnd/',
        ru: 'болтаться рядом',
        hy: 'ռռռ շրջել',
        ex: 'Stop hanging around and do something useful.',
      },
    ],
  },

  // SHOW
  {
    lv: 'A',
    cat: 'daily',
    type: 'phrasal',
    base: 'show',
    tr: '/ʃəʊ/',
    ru: 'показывать',
    hy: 'ցույց տալ',
    forms: [
      {
        w: 'show up',
        tr: '/ʃəʊ ʌp/',
        ru: 'появиться',
        hy: 'հայտնվել',
        ex: "He didn't show up to the meeting again.",
      },
      {
        w: 'show off',
        tr: '/ʃəʊ ɒf/',
        ru: 'хвастаться',
        hy: 'պարծենալ',
        ex: 'Stop showing off your new phone.',
      },
      {
        w: 'show around',
        tr: '/ʃəʊ əˈraʊnd/',
        ru: 'провести экскурсию',
        hy: 'շրջայց անցկացնել',
        ex: 'Let me show you around the city.',
      },
    ],
  },

  // FALL
  {
    lv: 'A',
    cat: 'people',
    type: 'phrasal',
    base: 'fall',
    tr: '/fɔːl/',
    ru: 'падать',
    hy: 'ընկնել',
    forms: [
      {
        w: 'fall for',
        tr: '/fɔːl fɔː/',
        ru: 'влюбиться / попасться',
        hy: 'սիրահարվել / խաբվել',
        ex: 'I fell for her the moment we met.',
      },
      {
        w: 'fall out',
        tr: '/fɔːl aʊt/',
        ru: 'поссориться',
        hy: 'կռվել',
        ex: 'They fell out over a small misunderstanding.',
      },
      {
        w: 'fall behind',
        tr: '/fɔːl bɪˈhaɪnd/',
        ru: 'отстать',
        hy: 'հետ մնալ',
        ex: "Don't fall behind with your assignments.",
      },
      {
        w: 'fall apart',
        tr: '/fɔːl əˈpɑːt/',
        ru: 'разваливаться',
        hy: 'փլուզվել',
        ex: 'Without a leader, the team fell apart.',
      },
    ],
  },

  // TEAR
  {
    lv: 'A',
    cat: 'object',
    type: 'phrasal',
    base: 'tear',
    tr: '/teə/',
    ru: 'рвать',
    hy: 'պատռել',
    forms: [
      {
        w: 'tear up',
        tr: '/teə ʌp/',
        ru: 'разорвать на куски',
        hy: 'մանր-մանր պատռել',
        ex: 'She tore up the letter and threw it away.',
      },
      {
        w: 'tear down',
        tr: '/teə daʊn/',
        ru: 'снести / разрушить',
        hy: 'քանդել',
        ex: 'They tore down the old building last year.',
      },
      {
        w: 'tear off',
        tr: '/teə ɒf/',
        ru: 'оторвать',
        hy: 'պոկել',
        ex: 'Tear off the price tag before gifting it.',
      },
    ],
  },

  // CRUMPLE / SCREW / MESS
  {
    lv: 'A',
    cat: 'object',
    type: 'phrasal',
    base: 'crumple / screw / mess',
    tr: '/ˈkrʌmpl/ /skruː/ /mes/',
    ru: 'мять / скомкать / облажаться',
    hy: 'ծռել / ձախողել / շփոթել',
    forms: [
      {
        w: 'crumple up',
        tr: '/ˈkrʌmpl ʌp/',
        ru: 'скомкать',
        hy: 'կռճռռ',
        ex: 'He crumpled up the paper and threw it away.',
      },
      {
        w: 'screw up',
        tr: '/skruː ʌp/',
        ru: 'скомкать / облажаться',
        hy: 'ձախողել',
        ex: 'I totally screwed up the presentation.',
      },
      {
        w: 'mess up',
        tr: '/mes ʌp/',
        ru: 'испортить / напутать',
        hy: 'խառնել / ձախողել',
        ex: 'Sorry, I messed up the schedule.',
      },
      {
        w: 'fold up',
        tr: '/fəʊld ʌp/',
        ru: 'сложить',
        hy: 'ծալել',
        ex: 'Fold up the map and put it in your bag.',
      },
    ],
  },

  // CUT
  {
    lv: 'A',
    cat: 'object',
    type: 'phrasal',
    base: 'cut',
    tr: '/kʌt/',
    ru: 'резать',
    hy: 'կտրել',
    forms: [
      {
        w: 'cut off',
        tr: '/kʌt ɒf/',
        ru: 'отрезать / отключить',
        hy: 'կտրել / անջատել',
        ex: 'They cut off the electricity after the storm.',
      },
      {
        w: 'cut down',
        tr: '/kʌt daʊn/',
        ru: 'сократить',
        hy: 'կրճատել',
        ex: 'You should cut down on sugar and coffee.',
      },
      {
        w: 'cut out',
        tr: '/kʌt aʊt/',
        ru: 'вырезать / перестать',
        hy: 'կտրել / դուրս կտրել',
        ex: "Cut it out! I'm trying to concentrate.",
      },
    ],
  },

  // STAND
  {
    lv: 'A',
    cat: 'people',
    type: 'phrasal',
    base: 'stand',
    tr: '/stænd/',
    ru: 'стоять',
    hy: 'կանգնել',
    forms: [
      {
        w: 'stand up',
        tr: '/stænd ʌp/',
        ru: 'встать / бросить (не прийти)',
        hy: 'վեր կենալ / չհայտնվել',
        ex: 'He stood me up — waited an hour for nothing.',
      },
      {
        w: 'stand up for',
        tr: '/stænd ʌp fɔː/',
        ru: 'защищать',
        hy: 'պաշտպանել',
        ex: 'Always stand up for what you believe in.',
      },
      {
        w: 'stand out',
        tr: '/stænd aʊt/',
        ru: 'выделяться',
        hy: 'աչքի ընկնել',
        ex: 'Her red dress made her stand out at the party.',
      },
      {
        w: 'stand by',
        tr: '/stænd baɪ/',
        ru: 'поддерживать / ждать',
        hy: 'կողքին կանգնել / սպասել',
        ex: "I'll stand by you no matter what.",
      },
    ],
  },

  // TALK
  {
    lv: 'A',
    cat: 'talk',
    type: 'phrasal',
    base: 'talk',
    tr: '/tɔːk/',
    ru: 'говорить',
    hy: 'խոսել',
    forms: [
      {
        w: 'talk into',
        tr: '/tɔːk ˈɪntə/',
        ru: 'уговорить',
        hy: 'համոզել',
        ex: 'She talked me into trying sushi for the first time.',
      },
      {
        w: 'talk out of',
        tr: '/tɔːk aʊt ɒv/',
        ru: 'отговорить',
        hy: 'հետ պահել (ինչ-որ բանից)',
        ex: 'I tried to talk him out of quitting.',
      },
      {
        w: 'talk over',
        tr: '/tɔːk ˈəʊvə/',
        ru: 'обсудить',
        hy: 'քննարկել',
        ex: "Let's talk it over before deciding.",
      },
      {
        w: 'talk back',
        tr: '/tɔːk bæk/',
        ru: 'дерзить / отвечать грубо',
        hy: 'կռահ պատասխանել',
        ex: "Don't talk back to your teacher.",
      },
    ],
  },

  // WORK
  {
    lv: 'A',
    cat: 'daily',
    type: 'phrasal',
    base: 'work',
    tr: '/wɜːk/',
    ru: 'работать',
    hy: 'աշխատել',
    forms: [
      {
        w: 'work out',
        tr: '/wɜːk aʊt/',
        ru: 'тренироваться / решиться',
        hy: 'մարզվել / լուծվել',
        ex: 'Everything will work out in the end.',
      },
      {
        w: 'work on',
        tr: '/wɜːk ɒn/',
        ru: 'работать над',
        hy: 'աշխատել (ինչ-որ բանի վրա)',
        ex: "I'm working on improving my pronunciation.",
      },
      {
        w: 'work up',
        tr: '/wɜːk ʌp/',
        ru: 'разозлить / взволновать',
        hy: 'հուզել',
        ex: "Don't work yourself up over small things.",
      },
    ],
  },

  // ═══════════ B-LEVEL WORDS ═══════════

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'acknowledge',
    tr: '/əkˈnɒlɪdʒ/',
    ru: 'признавать / подтверждать',
    hy: 'ճանաչել / հաստատել',
    ex: 'She acknowledged her mistake and apologised.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'assume',
    tr: '/əˈsjuːm/',
    ru: 'предполагать',
    hy: 'ենթադրել',
    ex: "Don't assume you know what others think.",
  },

  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'clarify',
    tr: '/ˈklærɪfaɪ/',
    ru: 'уточнить / прояснить',
    hy: 'պարզաբանել',
    ex: 'Could you clarify what you mean by that?',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'convince',
    tr: '/kənˈvɪns/',
    ru: 'убедить',
    hy: 'համոզել',
    ex: 'He finally convinced me to join the gym.',
  },

  {
    lv: 'B',
    cat: 'people',
    type: 'word',
    base: 'rely on',
    tr: '/rɪˈlaɪ ɒn/',
    ru: 'полагаться на',
    hy: 'ապավինել',
    ex: 'You can always rely on her to be honest.',
  },

  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'frustrated',
    tr: '/frʌˈstreɪtɪd/',
    ru: 'разочарованный / раздражённый',
    hy: 'հիասթափված',
    ex: "I get frustrated when I can't find the right word.",
  },

  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'overwhelmed',
    tr: '/ˌəʊvəˈwelmd/',
    ru: 'подавленный / захлёстнутый',
    hy: 'ճնշված',
    ex: 'I felt overwhelmed by all the new vocabulary.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'reckon',
    tr: '/ˈrekən/',
    ru: 'думаю / считаю (разг.)',
    hy: 'կարծում եմ',
    ex: "I reckon it'll take about an hour to get there.",
  },

  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'emphasise',
    tr: '/ˈemfəsaɪz/',
    ru: 'подчёркивать',
    hy: 'շեշտել',
    ex: 'She emphasised the importance of daily practice.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'negotiate',
    tr: '/nɪˈɡəʊʃieɪt/',
    ru: 'вести переговоры',
    hy: 'բանակցել',
    ex: 'They negotiated a better salary before signing.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'implement',
    tr: '/ˈɪmplɪment/',
    ru: 'внедрить / реализовать',
    hy: 'կիրառել',
    ex: 'We need to implement the new system by Friday.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'deadline',
    tr: '/ˈdedlaɪn/',
    ru: 'дедлайн / крайний срок',
    hy: 'վերջնաժամկետ',
    ex: 'The deadline for the project is next Monday.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'reflect on',
    tr: '/rɪˈflekt ɒn/',
    ru: 'размышлять / обдумывать',
    hy: 'մտորել',
    ex: "Take time to reflect on what you've learned.",
  },

  {
    lv: 'B',
    cat: 'people',
    type: 'word',
    base: 'colleague',
    tr: '/ˈkɒliːɡ/',
    ru: 'коллега',
    hy: 'գործընկեր',
    ex: 'My colleague speaks three languages fluently.',
  },

  {
    lv: 'B',
    cat: 'people',
    type: 'word',
    base: 'involve',
    tr: '/ɪnˈvɒlv/',
    ru: 'включать / вовлекать',
    hy: 'ներառել / ներգրավել',
    ex: 'The project involves a lot of teamwork.',
  },

  {
    lv: 'B',
    cat: 'daily',
    type: 'word',
    base: 'schedule',
    tr: '/ˈʃedjuːl/',
    ru: 'расписание / планировать',
    hy: 'ժամանակացույց',
    ex: 'I scheduled the meeting for Thursday morning.',
  },

  {
    lv: 'B',
    cat: 'daily',
    type: 'word',
    base: 'avoid',
    tr: '/əˈvɔɪd/',
    ru: 'избегать',
    hy: 'խուսափել',
    ex: 'Avoid making the same mistakes twice.',
  },

  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'cope with',
    tr: '/kəʊp wɪð/',
    ru: 'справляться с',
    hy: 'հաղթահարել',
    ex: 'How do you cope with stress at work?',
  },

  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'indicate',
    tr: '/ˈɪndɪkeɪt/',
    ru: 'указывать / обозначать',
    hy: 'ցույց տալ / նշել',
    ex: 'The report indicates a rise in sales.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'distinguish',
    tr: '/dɪˈstɪŋɡwɪʃ/',
    ru: 'различать',
    hy: 'տարբերել',
    ex: 'Can you distinguish between these two sounds?',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'approve',
    tr: '/əˈpruːv/',
    ru: 'одобрить',
    hy: 'հաստատել',
    ex: 'The manager approved the budget request.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'confirm',
    tr: '/kənˈfɜːm/',
    ru: 'подтвердить',
    hy: 'հաստատել',
    ex: 'Please confirm your attendance by email.',
  },

  {
    lv: 'B',
    cat: 'daily',
    type: 'word',
    base: 'habit',
    tr: '/ˈhæbɪt/',
    ru: 'привычка',
    hy: 'սովորություն',
    ex: 'Reading before bed is my favourite habit.',
  },

  {
    lv: 'B',
    cat: 'daily',
    type: 'word',
    base: 'routine',
    tr: '/ruːˈtiːn/',
    ru: 'рутина / распорядок',
    hy: 'ռուտին / ամենօրյա գործ',
    ex: 'A good morning routine sets the tone for the day.',
  },

  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'concerned',
    tr: '/kənˈsɜːnd/',
    ru: 'обеспокоенный',
    hy: 'անհանգիստ',
    ex: "I'm concerned about your progress.",
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'suppose',
    tr: '/səˈpəʊz/',
    ru: 'полагать / допускать',
    hy: 'ենթադրել',
    ex: 'I suppose we could try a different approach.',
  },

  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'argument',
    tr: '/ˈɑːɡjʊmənt/',
    ru: 'аргумент / спор',
    hy: 'փաստարկ / վեճ',
    ex: 'She made a strong argument for learning online.',
  },

  {
    lv: 'B',
    cat: 'people',
    type: 'word',
    base: 'relationship',
    tr: '/rɪˈleɪʃənʃɪp/',
    ru: 'отношения',
    hy: 'հարաբերություն',
    ex: 'Building good relationships takes time and effort.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'opportunity',
    tr: '/ˌɒpəˈtjuːnɪti/',
    ru: 'возможность',
    hy: 'հնարավորություն',
    ex: 'This job is a great opportunity to grow.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'efficient',
    tr: '/ɪˈfɪʃənt/',
    ru: 'эффективный',
    hy: 'արդյունավետ',
    ex: 'An efficient learner uses flashcards and speaks daily.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'perspective',
    tr: '/pəˈspektɪv/',
    ru: 'точка зрения / перспектива',
    hy: 'տեսակետ',
    ex: 'Try to see the problem from a different perspective.',
  },

  {
    lv: 'B',
    cat: 'daily',
    type: 'word',
    base: 'struggle',
    tr: '/ˈstrʌɡl/',
    ru: 'бороться / с трудом',
    hy: 'պայքարել / դժվարանալ',
    ex: 'I still struggle with English pronunciation.',
  },

  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'embarrassed',
    tr: '/ɪmˈbærəst/',
    ru: 'смущённый / конфузный',
    hy: 'ամոթ զգացող',
    ex: 'I was embarrassed when I mispronounced her name.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'realise',
    tr: '/ˈrɪəlaɪz/',
    ru: 'осознать',
    hy: 'գիտակցել',
    ex: 'I suddenly realised I had the wrong address.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'significant',
    tr: '/sɪɡˈnɪfɪkənt/',
    ru: 'значительный / важный',
    hy: 'զգալի / կարևոր',
    ex: 'There was a significant improvement after one month.',
  },

  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'achieve',
    tr: '/əˈtʃiːv/',
    ru: 'достичь',
    hy: 'հասնել',
    ex: 'You can achieve anything with consistent effort.',
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'phrasal',
    base: 'figure out',
    tr: '/ˈfɪɡər aʊt/',
    ru: 'разобраться / понять',
    hy: 'պարզել / հասկանալ',
    forms: [
      {
        w: 'figure out',
        tr: '/ˈfɪɡər aʊt/',
        ru: 'разобраться',
        hy: 'հասկանալ',
        ex: "I can't figure out how this grammar rule works.",
      },
    ],
  },

  {
    lv: 'B',
    cat: 'mind',
    type: 'phrasal',
    base: 'point out',
    tr: '/pɔɪnt aʊt/',
    ru: 'указать на / отметить',
    hy: 'մատնանշել',
    forms: [
      {
        w: 'point out',
        tr: '/pɔɪnt aʊt/',
        ru: 'указать на',
        hy: 'մատնանշել',
        ex: 'My teacher pointed out that I was using the wrong tense.',
      },
    ],
  },

  {
    lv: 'B',
    cat: 'talk',
    type: 'phrasal',
    base: 'bring up',
    tr: '/brɪŋ ʌp/',
    ru: 'поднять тему / вырастить',
    hy: 'բարձրացնել թեմա',
    forms: [
      {
        w: 'bring up',
        tr: '/brɪŋ ʌp/',
        ru: 'упомянуть / воспитать',
        hy: 'բարձրացնել / մեծացնել',
        ex: 'She brought up an interesting point in the meeting.',
      },
      {
        w: 'bring back',
        tr: '/brɪŋ bæk/',
        ru: 'вернуть / напомнить',
        hy: 'հետ բերել / հիշեցնել',
        ex: 'This song brings back happy memories.',
      },
      {
        w: 'bring about',
        tr: '/brɪŋ əˈbaʊt/',
        ru: 'привести к / вызвать',
        hy: 'բերել (ինչ-որ բանի)',
        ex: 'Hard work brings about real change.',
      },
    ],
  },

  {
    lv: 'B',
    cat: 'talk',
    type: 'phrasal',
    base: 'follow up',
    tr: '/ˈfɒləʊ ʌp/',
    ru: 'уточнить / проследить',
    hy: 'հետևել / ճշտել',
    forms: [
      {
        w: 'follow up',
        tr: '/ˈfɒləʊ ʌp/',
        ru: 'уточнить / проследить',
        hy: 'ճշտել',
        ex: "I'll follow up with an email after the meeting.",
      },
      {
        w: 'follow through',
        tr: '/ˈfɒləʊ θruː/',
        ru: 'доводить до конца',
        hy: 'հետևել մինչև վերջ',
        ex: "It's important to follow through on your promises.",
      },
    ],
  },

  {
    lv: 'B',
    cat: 'daily',
    type: 'phrasal',
    base: 'set up / set aside',
    tr: '/set ʌp/ /set əˈsaɪd/',
    ru: 'настроить / отложить в сторону',
    hy: 'կարգավորել / մի կողմ դնել',
    forms: [
      {
        w: 'set up',
        tr: '/set ʌp/',
        ru: 'настроить / организовать',
        hy: 'կարգավորել',
        ex: 'Set up your app and start practising today.',
      },
      {
        w: 'set aside',
        tr: '/set əˈsaɪd/',
        ru: 'отложить / зарезервировать',
        hy: 'մի կողմ դնել',
        ex: 'Set aside 30 minutes a day for vocabulary.',
      },
      {
        w: 'set off',
        tr: '/set ɒf/',
        ru: 'отправиться',
        hy: 'ճանապարհ ընկնել',
        ex: 'We set off early to avoid traffic.',
      },
    ],
  },

  {
    lv: 'B',
    cat: 'people',
    type: 'phrasal',
    base: 'back up',
    tr: '/bæk ʌp/',
    ru: 'поддержать / сохранить копию',
    hy: 'կրկնօրինակ / աջակցել',
    forms: [
      {
        w: 'back up',
        tr: '/bæk ʌp/',
        ru: 'поддержать / подкрепить',
        hy: 'կրկնօրինակ / աջակցել',
        ex: 'Back up your argument with examples.',
      },
      {
        w: 'back down',
        tr: '/bæk daʊn/',
        ru: 'отступить',
        hy: 'հետ քաշվել',
        ex: 'He backed down when he saw the evidence.',
      },
      {
        w: 'back out',
        tr: '/bæk aʊt/',
        ru: 'отказаться (в последний момент)',
        hy: 'հրաժարվել',
        ex: 'She backed out of the deal at the last minute.',
      },
    ],
  },

  // ═══════════ C-LEVEL WORDS ═══════════

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'articulate',
    tr: '/ɑːˈtɪkjʊlət/',
    ru: 'чётко выражать / красноречивый',
    hy: 'հստակ արտահայտել',
    ex: "She's incredibly articulate — every word is perfectly chosen.",
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'contemplate',
    tr: '/ˈkɒntəmpleɪt/',
    ru: 'созерцать / обдумывать',
    hy: 'խորհրդածել',
    ex: 'He contemplated the offer for several days before responding.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'ambiguous',
    tr: '/æmˈbɪɡjʊəs/',
    ru: 'двусмысленный',
    hy: 'երկիմաստ',
    ex: 'His answer was ambiguous — no one knew what he meant.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'meticulous',
    tr: '/mɪˈtɪkjʊləs/',
    ru: 'дотошный / тщательный',
    hy: 'մանրակրկիտ',
    ex: 'She is meticulous about checking every grammar point.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'pragmatic',
    tr: '/præɡˈmætɪk/',
    ru: 'прагматичный',
    hy: 'պրագմատիկ',
    ex: 'A pragmatic approach works better than perfectionism.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'unprecedented',
    tr: '/ʌnˈpresɪdentɪd/',
    ru: 'беспрецедентный',
    hy: 'աննախադեպ',
    ex: 'The speed of his progress was unprecedented.',
  },

  {
    lv: 'C',
    cat: 'talk',
    type: 'word',
    base: 'nuance',
    tr: '/ˈnjuːɑːns/',
    ru: 'нюанс',
    hy: 'նրբերང',
    ex: 'Understanding the nuances of English takes years.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'discern',
    tr: '/dɪˈsɜːn/',
    ru: 'различать / распознавать',
    hy: 'տարբերել / ճանաչել',
    ex: "It's hard to discern sarcasm in written text.",
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'rhetoric',
    tr: '/ˈretərɪk/',
    ru: 'риторика / пустые слова',
    hy: 'հռետորաբանություն',
    ex: 'His speech was full of rhetoric but said nothing new.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'eloquent',
    tr: '/ˈeləkwənt/',
    ru: 'красноречивый',
    hy: 'բանաստեղծ / հռետոր',
    ex: 'She gave an eloquent speech that moved the whole audience.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'juxtapose',
    tr: '/ˌdʒʌkstəˈpəʊz/',
    ru: 'сопоставить / противопоставить',
    hy: 'կողք-կողքի դնել',
    ex: 'The author juxtaposes wealth and poverty to highlight inequality.',
  },

  {
    lv: 'C',
    cat: 'emotion',
    type: 'word',
    base: 'exhilarating',
    tr: '/ɪɡˈzɪləreɪtɪŋ/',
    ru: 'захватывающий / бодрящий',
    hy: 'ոգևորող',
    ex: 'Speaking your first full sentence in English is exhilarating.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'scrutinise',
    tr: '/ˈskruːtɪnaɪz/',
    ru: 'тщательно изучить',
    hy: 'մանրակրկիտ ուսումնասիրել',
    ex: 'Every detail was scrutinised before the contract was signed.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'inherent',
    tr: '/ɪnˈhɪərənt/',
    ru: 'присущий / неотъемлемый',
    hy: 'բնորոշ / բնածին',
    ex: 'There is an inherent difficulty in learning tones in any language.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'mitigate',
    tr: '/ˈmɪtɪɡeɪt/',
    ru: 'смягчить / уменьшить',
    hy: 'մեղմել',
    ex: 'Regular practice helps mitigate the fear of speaking.',
  },

  {
    lv: 'C',
    cat: 'talk',
    type: 'word',
    base: 'imply',
    tr: '/ɪmˈplaɪ/',
    ru: 'подразумевать',
    hy: 'ենթադրել (ակնհայտ)',
    ex: 'Are you implying that I made a mistake?',
  },

  {
    lv: 'C',
    cat: 'talk',
    type: 'word',
    base: 'elaborate',
    tr: '/ɪˈlæbərət/',
    ru: 'подробно рассказать',
    hy: 'մանրամասնել',
    ex: 'Could you elaborate on what you mean by that?',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'inevitable',
    tr: '/ɪnˈevɪtəbl/',
    ru: 'неизбежный',
    hy: 'անխուսափելի',
    ex: 'Making mistakes is inevitable when learning a language.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'paradox',
    tr: '/ˈpærədɒks/',
    ru: 'парадокс',
    hy: 'պարադոքս',
    ex: 'The paradox of language learning: you improve by making mistakes.',
  },

  {
    lv: 'C',
    cat: 'emotion',
    type: 'word',
    base: 'apprehensive',
    tr: '/ˌæprɪˈhensɪv/',
    ru: 'встревоженный / опасающийся',
    hy: 'մտահոգ / վախեցած',
    ex: 'I was apprehensive before my first English job interview.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'lucid',
    tr: '/ˈluːsɪd/',
    ru: 'ясный / понятный',
    hy: 'հստակ / պարզ',
    ex: 'A lucid explanation makes even complex topics easy to grasp.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'subconscious',
    tr: '/ˌsʌbˈkɒnʃəs/',
    ru: 'подсознательный',
    hy: 'ենթагիտակցական',
    ex: 'Language fluency happens when it moves into the subconscious.',
  },

  {
    lv: 'C',
    cat: 'people',
    type: 'word',
    base: 'rapport',
    tr: '/ræˈpɔː/',
    ru: 'взаимопонимание / доверие',
    hy: 'փոխըմբռնում',
    ex: 'Building rapport with native speakers accelerates learning.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'concise',
    tr: '/kənˈsaɪs/',
    ru: 'лаконичный',
    hy: 'հակիրճ',
    ex: 'Keep your emails concise — nobody reads long messages.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'coherent',
    tr: '/kəʊˈhɪərənt/',
    ru: 'последовательный / связный',
    hy: 'հետևողական',
    ex: 'Your argument is well-structured and coherent.',
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'grasp',
    tr: '/ɡrɑːsp/',
    ru: 'понять / схватить суть',
    hy: 'ըմբռնել',
    ex: 'Once you grasp the grammar rule, everything clicks.',
  },

  {
    lv: 'C',
    cat: 'emotion',
    type: 'word',
    base: 'resilient',
    tr: '/rɪˈzɪliənt/',
    ru: 'стойкий / устойчивый',
    hy: 'դիմացկուն',
    ex: 'Resilient learners bounce back after failures.',
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'subtle',
    tr: '/ˈsʌtl/',
    ru: 'тонкий / едва уловимый',
    hy: 'նուրբ / դժվար նկատելի',
    ex: "There is a subtle difference between 'bring' and 'take'.",
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'straightforward',
    tr: '/ˌstreɪtˈfɔːwəd/',
    ru: 'простой / прямой',
    hy: 'ուղիղ / պարզ',
    ex: 'The instructions were straightforward and easy to follow.',
  },

  {
    lv: 'C',
    cat: 'talk',
    type: 'phrasal',
    base: 'account for',
    tr: '/əˈkaʊnt fɔː/',
    ru: 'объяснять / составлять (долю)',
    hy: 'բացատրել',
    forms: [
      {
        w: 'account for',
        tr: '/əˈkaʊnt fɔː/',
        ru: 'объяснять',
        hy: 'բացատրել',
        ex: 'How do you account for such rapid progress?',
      },
    ],
  },

  {
    lv: 'C',
    cat: 'mind',
    type: 'phrasal',
    base: 'delve into',
    tr: '/delv ˈɪntə/',
    ru: 'углубиться / детально изучить',
    hy: 'խորանալ',
    forms: [
      {
        w: 'delve into',
        tr: '/delv ˈɪntə/',
        ru: 'углубиться в',
        hy: 'խորանալ',
        ex: "Let's delve into the finer points of C1 grammar.",
      },
    ],
  },

  {
    lv: 'C',
    cat: 'formal',
    type: 'phrasal',
    base: 'give rise to',
    tr: '/ɡɪv raɪz tə/',
    ru: 'порождать / давать начало',
    hy: 'հանգեցնել',
    forms: [
      {
        w: 'give rise to',
        tr: '/ɡɪv raɪz tə/',
        ru: 'порождать',
        hy: 'հանգեցնել',
        ex: 'Inconsistent rules give rise to a lot of confusion.',
      },
    ],
  },

  {
    lv: 'C',
    cat: 'talk',
    type: 'phrasal',
    base: 'draw on',
    tr: '/drɔː ɒn/',
    ru: 'использовать / опираться на',
    hy: 'օգտագործել (փորձ)',
    forms: [
      {
        w: 'draw on',
        tr: '/drɔː ɒn/',
        ru: 'опираться на (опыт)',
        hy: 'հիմնվել (փորձի վրա)',
        ex: 'She drew on years of experience to solve the problem.',
      },
      {
        w: 'draw up',
        tr: '/drɔː ʌp/',
        ru: 'составить (документ)',
        hy: 'կազմել (փաստաթուղթ)',
        ex: 'Draw up a plan before you start the project.',
      },
    ],
  },

  // ═══ MEGA EXTENSION (B2–C1) ═══

  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'arguably',
    tr: '/ˈɑːɡjuəbli/',
    ru: 'можно утверждать / по мнению многих',
    hy: 'հավանաբար / կարելի է պնդել',
    ex: 'She is arguably the strongest writer in our cohort.',
  },
  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'admittedly',
    tr: '/ədˈmɪtɪdli/',
    ru: 'признаться / если честно',
    hy: 'ընդունելիորեն / խոստովանենք',
    ex: 'Admittedly, I still mix up the perfect tenses under stress.',
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'nuanced',
    tr: '/ˈnjuːɑːnst/',
    ru: 'нюансированный',
    hy: 'նրբերանգավոր',
    ex: 'Native replies sound more nuanced than textbook answers.',
  },
  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'viable',
    tr: '/ˈvaɪəbl/',
    ru: 'жизнеспособный / реальный',
    hy: 'կենսունակ / իրագործելի',
    ex: 'Is remote pair practice a viable way to improve fluency?',
  },
  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'feasible',
    tr: '/ˈfiːzəbl/',
    ru: 'осуществимый',
    hy: 'իրագործելի',
    ex: 'A ten-minute daily drill is feasible even on travel days.',
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'trade-off',
    tr: '/ˈtreɪd ɒf/',
    ru: 'компромисс / обмен',
    hy: 'կոմպրոմիս / փոխանակում',
    ex: "There's always a trade-off between speed and accuracy.",
  },
  {
    lv: 'B',
    cat: 'daily',
    type: 'word',
    base: 'bottleneck',
    tr: '/ˈbɒtlnek/',
    ru: 'узкое место (процесса)',
    hy: 'սեղմված կետ',
    ex: 'Pronunciation became the bottleneck in my IELTS prep.',
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'workaround',
    tr: '/ˈwɜːkəraʊnd/',
    ru: 'обходной путь',
    hy: 'զիջումային լուծում',
    ex: 'Using transcripts first was a smart workaround for fast audio.',
  },
  {
    lv: 'B',
    cat: 'formal',
    type: 'word',
    base: 'caveat',
    tr: '/ˈkæviæt/',
    ru: 'оговорка / предупреждение',
    hy: 'նախազգուշացում',
    ex: 'One caveat: these rules vary by region.',
  },
  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'granular',
    tr: '/ˈɡrænjələ/',
    ru: 'детальный / пошаговый',
    hy: 'մանրամասն',
    ex: 'I need more granular feedback on sentence stress.',
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'holistic',
    tr: '/həʊˈlɪstɪk/',
    ru: 'целостный / системный',
    hy: 'ամբողջական',
    ex: 'A holistic plan covers input, output, and review.',
  },
  {
    lv: 'B',
    cat: 'people',
    type: 'word',
    base: 'stakeholder',
    tr: '/ˈsteɪkhəʊldə/',
    ru: 'заинтересованная сторона',
    hy: 'շահառու',
    ex: 'Remember to brief every stakeholder before the policy change.',
  },
  {
    lv: 'B',
    cat: 'talk',
    type: 'phrasal',
    base: 'run by',
    tr: '/rʌn baɪ/',
    ru: 'прогнать мысль мимо кого-то',
    hy: 'ներկայացնել (գաղափար)',
    forms: [
      {
        w: 'run by',
        tr: '/rʌn baɪ/',
        ru: 'прогнать идею мимо кого-л.',
        hy: 'քննարկել (մեկի հետ)',
        ex: 'Let me run this outline by you before I submit.',
      },
      {
        w: 'run through',
        tr: '/rʌn θruː/',
        ru: 'быстро пройти / репетиция',
        hy: 'անցկացնել (վարժություն)',
        ex: "We'll run through the tricky vowels once more.",
      },
    ],
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'phrasal',
    base: 'boil down to',
    tr: '/bɔɪl daʊn tə/',
    ru: 'сводиться к',
    hy: 'եզրափակվել',
    forms: [
      {
        w: 'boil down to',
        tr: '/bɔɪl daʊn tə/',
        ru: 'сводиться к одному',
        hy: 'կարևորն այս է',
        ex: 'It boils down to consistent spaced repetition.',
      },
    ],
  },
  {
    lv: 'B',
    cat: 'emotion',
    type: 'phrasal',
    base: 'grow on',
    tr: '/ɡrəʊ ɒn/',
    ru: 'начать нравиться со временем',
    hy: 'սիրել դառնալ (ժամանակի ընթացքում)',
    forms: [
      {
        w: 'grow on',
        tr: '/ɡrəʊ ɒn/',
        ru: 'впечатлить со временем',
        hy: 'դուր գալ աստիճանաբար',
        ex: 'This podcast grew on me after three episodes.',
      },
    ],
  },
  {
    lv: 'B',
    cat: 'daily',
    type: 'phrasal',
    base: 'wear off',
    tr: '/weər ɒf/',
    ru: 'проходить (о действии)',
    hy: 'անջատվել (ազդեցությունից)',
    forms: [
      {
        w: 'wear off',
        tr: '/weər ɒf/',
        ru: 'ослабеть / пройти',
        hy: 'թուլանալ',
        ex: 'The caffeine buzz wore off right before the listening section.',
      },
    ],
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'phrasal',
    base: 'pan out',
    tr: '/pæn aʊt/',
    ru: 'сложиться / увенчаться успехом',
    hy: 'լուծվել (արդյունքում)',
    forms: [
      {
        w: 'pan out',
        tr: '/pæn aʊt/',
        ru: 'закончиться исходом',
        hy: 'ավարտվել (արդյունքով)',
        ex: "We'll see how the experiment pans out after a month.",
      },
    ],
  },
  {
    lv: 'B',
    cat: 'talk',
    type: 'phrasal',
    base: 'open up',
    tr: '/ˈəʊpən ʌp/',
    ru: 'открыться / расшириться',
    hy: 'բացվել (զգացմունքային)',
    forms: [
      {
        w: 'open up',
        tr: '/ˈəʊpən ʌp/',
        ru: 'говорить откровеннее',
        hy: 'ավելի բաց խոսել',
        ex: 'She only opened up after we switched to her native language.',
      },
    ],
  },
  {
    lv: 'B',
    cat: 'formal',
    type: 'phrasal',
    base: 'feed into',
    tr: '/fiːd ˈɪntə/',
    ru: 'впитываться / вести к',
    hy: 'սնել / մտնել (մեջ)',
    forms: [
      {
        w: 'feed into',
        tr: '/fiːd ˈɪntə/',
        ru: 'влиять на следующий этап',
        hy: 'ազդել հաջորդ փուլի վրա',
        ex: 'Drills should feed into spontaneous speech, not replace it.',
      },
    ],
  },
  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'pragmatically',
    tr: '/præɡˈmætɪkli/',
    ru: 'прагматично',
    hy: 'պրագմատիկորեն',
    ex: 'Pragmatically, you should record baseline audio before coaching.',
  },
  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'heuristic',
    tr: '/hjʊəˈrɪstɪk/',
    ru: 'эвристика / правило большого пальца',
    hy: 'էվրիստիկա',
    ex: 'Shadowing is a useful heuristic, not a law of physics.',
  },
  {
    lv: 'C',
    cat: 'talk',
    type: 'word',
    base: 'rhetorically',
    tr: '/rɪˈtɒrɪkli/',
    ru: 'риторически',
    hy: 'հռետորաբանորեն',
    ex: 'Rhetorically, the question already assumes agreement.',
  },
  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'systemic',
    tr: '/sɪˈstemɪk/',
    ru: 'системный (в системе)',
    hy: 'համակարգային',
    ex: 'Systemic bias in tests is harder to fix than typos.',
  },
  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'idiosyncrasy',
    tr: '/ˌɪdiəˈsɪŋkrəsi/',
    ru: 'особенность / индивидуальная черта',
    hy: 'իդիոսինկրազիա',
    ex: 'Every dialect has its charming idiosyncrasies.',
  },
  {
    lv: 'C',
    cat: 'talk',
    type: 'word',
    base: 'verbatim',
    tr: '/vɜːˈbeɪtɪm/',
    ru: 'дословно',
    hy: 'բառացիորեն',
    ex: 'Quote the examiner verbatim before you argue with the rubric.',
  },
  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'a priori',
    tr: '/ˌeɪ praɪˈɔːraɪ/',
    ru: 'априори / заранее',
    hy: 'ա պրիորի',
    ex: "We shouldn't reject shadowing a priori without trying it.",
  },
  {
    lv: 'C',
    cat: 'mind',
    type: 'phrasal',
    base: 'zero in on',
    tr: '/ˈzɪərəʊ ɪn ɒn/',
    ru: 'сфокусироваться на',
    hy: 'կենտրոնանալ',
    forms: [
      {
        w: 'zero in on',
        tr: '/ˈzɪərəʊ ɪn ɒn/',
        ru: 'нацелиться',
        hy: 'կենտրոնանալ',
        ex: "Let's zero in on linking /r/ across word boundaries.",
      },
    ],
  },
  {
    lv: 'C',
    cat: 'talk',
    type: 'phrasal',
    base: 'touch on',
    tr: '/tʌtʃ ɒn/',
    ru: 'слегка затронуть',
    hy: 'թեթևակի անդրադառնալ',
    forms: [
      {
        w: 'touch on',
        tr: '/tʌtʃ ɒn/',
        ru: 'упомянуть вскользь',
        hy: 'թեթևակի անդրադառնել',
        ex: 'The course only touched on intonation in the last week.',
      },
    ],
  },
  {
    lv: 'C',
    cat: 'people',
    type: 'phrasal',
    base: 'relate to',
    tr: '/rɪˈleɪt tə/',
    ru: 'понимать / быть близким по опыту',
    hy: 'համակերպվել',
    forms: [
      {
        w: 'relate to',
        tr: '/rɪˈleɪt tə/',
        ru: 'сопереживать / понимать',
        hy: 'հասկանալ (զգացումով)',
        ex: 'Listeners relate to stories about embarrassing mistakes.',
      },
    ],
  },
  {
    lv: 'C',
    cat: 'daily',
    type: 'phrasal',
    base: 'factor in',
    tr: '/ˈfæktər ɪn/',
    ru: 'учесть / включить в расчёт',
    hy: 'հաշվի առնել',
    forms: [
      {
        w: 'factor in',
        tr: '/ˈfæktər ɪn/',
        ru: 'учесть переменную',
        hy: 'ներառել հաշվարկում',
        ex: 'Factor in fatigue when you schedule mock exams.',
      },
    ],
  },
  {
    lv: 'C',
    cat: 'formal',
    type: 'phrasal',
    base: 'hinge on',
    tr: '/hɪndʒ ɒn/',
    ru: 'зависеть от',
    hy: 'կախված լինել',
    forms: [
      {
        w: 'hinge on',
        tr: '/hɪndʒ ɒn/',
        ru: 'вертеться вокруг / зависеть',
        hy: 'կախված լինել',
        ex: 'The appeal hinges on one ambiguous sentence.',
      },
    ],
  },
  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'daunting',
    tr: '/ˈdɔːntɪŋ/',
    ru: 'пугающий / обескураживающий',
    hy: 'վախեցնող',
    ex: 'C1 interviews look daunting until you break them into chunks.',
  },
  {
    lv: 'B',
    cat: 'emotion',
    type: 'word',
    base: 'reassuring',
    tr: '/ˌriːəˈʃʊərɪŋ/',
    ru: 'успокаивающий',
    hy: 'հանգստացնող',
    ex: 'A reassuring tutor normalises plateau phases.',
  },
  {
    lv: 'B',
    cat: 'mind',
    type: 'word',
    base: 'insightful',
    tr: '/ˈɪnsaɪtfəl/',
    ru: 'глубокий / проницательный',
    hy: 'խորքային',
    ex: 'Her feedback was blunt but insightful.',
  },
  {
    lv: 'B',
    cat: 'talk',
    type: 'word',
    base: 'off-topic',
    tr: '/ɒf ˈtɒpɪk/',
    ru: 'не по теме',
    hy: 'թեմայից դուրս',
    ex: "Let's stay off-topic for a minute — how was the conference?",
  },
  {
    lv: 'C',
    cat: 'talk',
    type: 'word',
    base: 'tacit',
    tr: '/ˈtæsɪt/',
    ru: 'подразумеваемый / молчаливый',
    hy: 'թաքնյա',
    ex: 'There was tacit agreement that phones stay in bags.',
  },
  {
    lv: 'C',
    cat: 'formal',
    type: 'word',
    base: 'redundant',
    tr: '/rɪˈdʌndənt/',
    ru: 'избыточный',
    hy: 'ավելորդ',
    ex: "Calling it 'PIN number' is redundant but common.",
  },
  {
    lv: 'C',
    cat: 'mind',
    type: 'word',
    base: 'orthogonal',
    tr: '/ɔːˈθɒɡənl/',
    ru: 'независимый / перпендикулярный (мат.)',
    hy: 'օրթոգոնալ',
    ex: 'Pronunciation and grammar errors are somewhat orthogonal problems.',
  },
];
