export const data = [
  // ═══ ДВИЖЕНИЕ (motion) ═══
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'put',
    base_ru: 'класть / ставить',
    forms: [
      {
        w: 'put on',
        m: 'надевать',
        ex: "Put on your coat, it's cold.",
        exRu: 'Надень пальто, холодно.',
      },
      {
        w: 'put off',
        m: 'откладывать',
        ex: "Don't put off till tomorrow.",
        exRu: 'Не откладывайте на завтра.',
      },
      {
        w: 'put down',
        m: 'положить вниз / унижать',
        ex: 'Put your phone down.',
        exRu: 'Отложите телефон.',
      },
      {
        w: 'put up',
        m: 'поднять / повесить',
        ex: 'Put up a picture on the wall.',
        exRu: 'Повесьте картинку на стену.',
      },
      {
        w: 'put out',
        m: 'потушить',
        ex: 'Put out the fire!',
        exRu: 'Потушите огонь!',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'get',
    base_ru: 'получать / становиться',
    forms: [
      {
        w: 'get up',
        m: 'вставать',
        ex: 'I get up at 7 every day.',
        exRu: 'Я встаю в 7 каждый день.',
      },
      {
        w: 'get in',
        m: 'войти / сесть в',
        ex: 'Get in the car.',
        exRu: 'Садись в машину.',
      },
      {
        w: 'get out',
        m: 'выйти',
        ex: 'Get out of here!',
        exRu: 'Уйди отсюда!',
      },
      {
        w: 'get on',
        m: 'садиться (автобус)',
        ex: 'Get on the bus.',
        exRu: 'Садитесь в автобус.',
      },
      {
        w: 'get off',
        m: 'выходить (транспорт)',
        ex: 'Get off at the next stop.',
        exRu: 'Выходите на следующей остановке.',
      },
      {
        w: 'get back',
        m: 'вернуться',
        ex: 'When do you get back?',
        exRu: 'Когда ты вернешься?',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'go',
    base_ru: 'идти / ехать',
    forms: [
      {
        w: 'go on',
        m: 'продолжать',
        ex: "Go on, I'm listening.",
        exRu: 'Давай, я слушаю.',
      },
      {
        w: 'go out',
        m: 'выходить / встречаться',
        ex: "Let's go out tonight.",
        exRu: 'Давай выйдем сегодня вечером.',
      },
      {
        w: 'go back',
        m: 'возвращаться',
        ex: 'I want to go back home.',
        exRu: 'Я хочу вернуться домой.',
      },
      {
        w: 'go away',
        m: 'уйти / уехать',
        ex: 'Go away, please.',
        exRu: 'Уйди, пожалуйста.',
      },
      {
        w: 'go through',
        m: 'пережить / просмотреть',
        ex: 'Go through your notes.',
        exRu: 'Просмотрите свои записи.',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'come',
    base_ru: 'приходить',
    forms: [
      {
        w: 'come in',
        m: 'войди',
        ex: 'Come in, the door is open.',
        exRu: 'Заходите, дверь открыта.',
      },
      {
        w: 'come back',
        m: 'вернуться',
        ex: 'Come back soon!',
        exRu: 'Возвращайся скорее!',
      },
      {
        w: 'come on',
        m: 'давай / поторопись',
        ex: "Come on, we're late!",
        exRu: 'Давай, мы опаздываем!',
      },
      {
        w: 'come up',
        m: 'подойти / возникнуть',
        ex: 'A problem came up.',
        exRu: 'Возникла проблема.',
      },
      {
        w: 'come across',
        m: 'наткнуться на',
        ex: 'I came across a great book.',
        exRu: 'Мне попалась отличная книга.',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'run',
    base_ru: 'бежать / работать',
    forms: [
      {
        w: 'run out',
        m: 'закончиться',
        ex: 'We ran out of milk.',
        exRu: 'У нас закончилось молоко.',
      },
      {
        w: 'run away',
        m: 'убежать',
        ex: "Don't run away from problems.",
        exRu: 'Не убегайте от проблем.',
      },
      {
        w: 'run into',
        m: 'случайно встретить',
        ex: 'I ran into an old friend.',
        exRu: 'Я встретил старого друга.',
      },
      {
        w: 'run over',
        m: 'сбить / переехать',
        ex: 'He was run over by a car.',
        exRu: 'Его сбила машина.',
      },
    ],
  },

  // ═══ ПРЕДМЕТЫ / ДЕЙСТВИЯ (object) ═══
  {
    cat: 'object',
    type: 'phrasal',
    base: 'pick',
    base_ru: 'брать / выбирать',
    forms: [
      {
        w: 'pick up',
        m: 'поднять / забрать',
        ex: 'Pick up the keys, please.',
        exRu: 'Возьмите ключи, пожалуйста.',
      },
      {
        w: 'pick out',
        m: 'выбрать',
        ex: 'Pick out a shirt for tonight.',
        exRu: 'Выбери рубашку на вечер.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'throw',
    base_ru: 'бросать',
    forms: [
      {
        w: 'throw away',
        m: 'выбросить',
        ex: 'Throw away old papers.',
        exRu: 'Выбросьте старые бумаги.',
      },
      {
        w: 'throw up',
        m: 'вырвать (тошнота)',
        ex: 'I felt sick and threw up.',
        exRu: 'Мне стало плохо, и меня вырвало.',
      },
      {
        w: 'throw in',
        m: 'добавить бесплатно',
        ex: 'They threw in a free gift.',
        exRu: 'Подкинули бесплатный подарок.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'tear',
    base_ru: 'рвать',
    forms: [
      {
        w: 'tear up',
        m: 'разорвать на куски',
        ex: 'She tore up the letter.',
        exRu: 'Она порвала письмо.',
      },
      {
        w: 'tear down',
        m: 'сломать / снести',
        ex: 'They tore down the old building.',
        exRu: 'Снесли старое здание.',
      },
      {
        w: 'tear off',
        m: 'оторвать',
        ex: 'Tear off the label.',
        exRu: 'Оторвите этикетку.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'crumple / screw',
    base_ru: 'мять / скомкать',
    forms: [
      {
        w: 'crumple up',
        m: 'скомкать',
        ex: 'He crumpled up the paper.',
        exRu: 'Он скомкал бумагу.',
      },
      {
        w: 'screw up',
        m: 'скомкать / облажаться',
        ex: "Don't screw up this time.",
        exRu: 'Не облажайся на этот раз.',
      },
      {
        w: 'mess up',
        m: 'испортить / напутать',
        ex: 'I totally messed up the test.',
        exRu: 'Я полностью испортил тест.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'break',
    base_ru: 'ломать',
    forms: [
      {
        w: 'break up',
        m: 'расстаться / распасться',
        ex: 'They broke up last week.',
        exRu: 'Они расстались на прошлой неделе.',
      },
      {
        w: 'break down',
        m: 'сломаться / расплакаться',
        ex: 'My car broke down.',
        exRu: 'Моя машина сломалась.',
      },
      {
        w: 'break in',
        m: 'взломать / прервать',
        ex: 'He broke into the house.',
        exRu: 'Он ворвался в дом.',
      },
      {
        w: 'break out',
        m: 'вырваться / вспыхнуть',
        ex: 'Fire broke out at night.',
        exRu: 'Пожар произошел ночью.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'cut',
    base_ru: 'резать',
    forms: [
      {
        w: 'cut off',
        m: 'отрезать / отключить',
        ex: 'They cut off the electricity.',
        exRu: 'Они отключили электричество.',
      },
      {
        w: 'cut down',
        m: 'сократить / срубить',
        ex: 'Cut down on sugar.',
        exRu: 'Сократите употребление сахара.',
      },
      {
        w: 'cut out',
        m: 'вырезать / перестать',
        ex: 'Cut it out! Stop it.',
        exRu: 'Вырежьте это! Прекрати это.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'turn',
    base_ru: 'поворачивать / включать',
    forms: [
      {
        w: 'turn on',
        m: 'включить',
        ex: 'Turn on the light.',
        exRu: 'Включите свет.',
      },
      {
        w: 'turn off',
        m: 'выключить',
        ex: 'Turn off your phone.',
        exRu: 'Выключите телефон.',
      },
      {
        w: 'turn up',
        m: 'прибавить громкость / появиться',
        ex: 'Turn up the music!',
        exRu: 'Включи музыку!',
      },
      {
        w: 'turn down',
        m: 'убавить / отказать',
        ex: 'He turned down the offer.',
        exRu: 'Он отклонил предложение.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'give',
    base_ru: 'давать / отдавать',
    forms: [
      {
        w: 'give up',
        m: 'сдаться',
        ex: 'Never give up!',
        exRu: 'Никогда не сдавайся!',
      },
      {
        w: 'give out',
        m: 'раздать / кончиться',
        ex: 'Give out the papers.',
        exRu: 'Раздайте бумаги.',
      },
      {
        w: 'give back',
        m: 'вернуть',
        ex: 'Give back my book.',
        exRu: 'Верните мою книгу.',
      },
      {
        w: 'give in',
        m: 'уступить',
        ex: 'He finally gave in.',
        exRu: 'Наконец он сдался.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'take',
    base_ru: 'брать',
    forms: [
      {
        w: 'take off',
        m: 'снять / взлетать',
        ex: 'Take off your shoes.',
        exRu: 'Снимите обувь.',
      },
      {
        w: 'take on',
        m: 'взять на себя',
        ex: 'I took on a new project.',
        exRu: 'Я взялся за новый проект.',
      },
      {
        w: 'take out',
        m: 'вынуть / пойти куда-то',
        ex: 'Take out the trash.',
        exRu: 'Вынесите мусор.',
      },
      {
        w: 'take over',
        m: 'взять под контроль',
        ex: 'He took over the company.',
        exRu: 'Он взял на себя управление компанией.',
      },
      {
        w: 'take up',
        m: 'заняться чем-то',
        ex: 'I took up painting.',
        exRu: 'Я занялся рисованием.',
      },
    ],
  },

  // ═══ ЛЮДИ / ОТНОШЕНИЯ (relation) ═══
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'look',
    base_ru: 'смотреть',
    forms: [
      {
        w: 'look for',
        m: 'искать',
        ex: "I'm looking for my keys.",
        exRu: 'Я ищу свои ключи.',
      },
      {
        w: 'look after',
        m: 'присматривать',
        ex: 'Can you look after the kids?',
        exRu: 'Сможешь ли ты присмотреть за детьми?',
      },
      {
        w: 'look up',
        m: 'найти информацию',
        ex: 'Look up the word in a dictionary.',
        exRu: 'Найдите слово в словаре.',
      },
      {
        w: 'look down on',
        m: 'смотреть свысока',
        ex: "Don't look down on others.",
        exRu: 'Не смотрите на других свысока.',
      },
      {
        w: 'look forward to',
        m: 'с нетерпением ждать',
        ex: 'I look forward to seeing you.',
        exRu: 'Я с нетерпением жду встречи с вами.',
      },
    ],
  },
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'bring',
    base_ru: 'приносить',
    forms: [
      {
        w: 'bring up',
        m: 'поднять тему / вырастить',
        ex: "Don't bring up that topic.",
        exRu: 'Не поднимайте эту тему.',
      },
      {
        w: 'bring back',
        m: 'вернуть / напомнить',
        ex: 'This song brings back memories.',
        exRu: 'Эта песня навевает воспоминания.',
      },
      {
        w: 'bring in',
        m: 'пригласить / принести доход',
        ex: 'Bring in the expert.',
        exRu: 'Пригласите эксперта.',
      },
    ],
  },
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'fall',
    base_ru: 'падать',
    forms: [
      {
        w: 'fall for',
        m: 'влюбиться / попасться',
        ex: 'I fell for her smile.',
        exRu: 'Я влюбился в ее улыбку.',
      },
      {
        w: 'fall out',
        m: 'поссориться',
        ex: 'We fell out over money.',
        exRu: 'Мы поссорились из-за денег.',
      },
      {
        w: 'fall behind',
        m: 'отстать',
        ex: "Don't fall behind in class.",
        exRu: 'Не отставайте в классе.',
      },
      {
        w: 'fall apart',
        m: 'разваливаться',
        ex: 'Everything is falling apart.',
        exRu: 'Все разваливается.',
      },
    ],
  },
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'stand',
    base_ru: 'стоять',
    forms: [
      {
        w: 'stand up',
        m: 'встать / бросить (не прийти)',
        ex: 'He stood me up at the cafe.',
        exRu: 'Он поддержал меня в кафе.',
      },
      {
        w: 'stand up for',
        m: 'защищать',
        ex: 'Stand up for yourself!',
        exRu: 'Постойте за себя!',
      },
      {
        w: 'stand out',
        m: 'выделяться',
        ex: 'She really stands out.',
        exRu: 'Она действительно выделяется.',
      },
      {
        w: 'stand by',
        m: 'поддерживать / ждать',
        ex: 'Stand by me.',
        exRu: 'Останься со мной.',
      },
    ],
  },
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'make',
    base_ru: 'делать',
    forms: [
      {
        w: 'make up',
        m: 'помириться / придумать',
        ex: 'They made up after the fight.',
        exRu: 'Они помирились после боя.',
      },
      {
        w: 'make out',
        m: 'разобрать / целоваться',
        ex: "I can't make out what he said.",
        exRu: 'Я не могу разобрать, что он сказал.',
      },
      {
        w: 'make up for',
        m: 'компенсировать',
        ex: "I'll make up for being late.",
        exRu: 'Я компенсирую опоздание.',
      },
      {
        w: 'make fun of',
        m: 'смеяться над',
        ex: "Don't make fun of others.",
        exRu: 'Не смейтесь над другими.',
      },
    ],
  },

  // ═══ ЭМОЦИИ (emotion) ═══
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'cheer',
    base_ru: 'радовать',
    forms: [
      {
        w: 'cheer up',
        m: 'взбодриться / подбодрить',
        ex: "Cheer up! It's not that bad.",
        exRu: 'Не унывать! Это не так уж и плохо.',
      },
      {
        w: 'cheer on',
        m: 'поддерживать криком',
        ex: 'The crowd cheered on the team.',
        exRu: 'Публика подбадривала команду.',
      },
    ],
  },
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'calm',
    base_ru: 'успокаивать',
    forms: [
      {
        w: 'calm down',
        m: 'успокоиться',
        ex: 'Calm down, everything is fine.',
        exRu: 'Успокойся, все в порядке.',
      },
    ],
  },
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'hold',
    base_ru: 'держать',
    forms: [
      {
        w: 'hold on',
        m: 'подождать / держаться',
        ex: 'Hold on a second.',
        exRu: 'Подожди секунду.',
      },
      {
        w: 'hold back',
        m: 'сдерживать',
        ex: 'She held back her tears.',
        exRu: 'Она сдержала слезы.',
      },
      {
        w: 'hold out',
        m: 'выдержать',
        ex: 'Can you hold out a bit longer?',
        exRu: 'Можешь продержаться еще немного?',
      },
    ],
  },
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'let',
    base_ru: 'позволять',
    forms: [
      {
        w: 'let down',
        m: 'разочаровать',
        ex: "Don't let me down.",
        exRu: 'Не подведи меня.',
      },
      {
        w: 'let go',
        m: 'отпустить',
        ex: 'Let go of the past.',
        exRu: 'Отпустите прошлое.',
      },
      {
        w: 'let out',
        m: 'выпустить / выразить',
        ex: 'Let out a big sigh.',
        exRu: 'Испусти большой вздох.',
      },
    ],
  },
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'work',
    base_ru: 'работать',
    forms: [
      {
        w: 'work out',
        m: 'тренироваться / решить',
        ex: 'It all worked out fine.',
        exRu: 'Все получилось хорошо.',
      },
      {
        w: 'work on',
        m: 'работать над',
        ex: "I'm working on my English.",
        exRu: 'Я работаю над своим английским.',
      },
      {
        w: 'work up',
        m: 'разозлить / взбодрить',
        ex: "Don't work yourself up.",
        exRu: 'Не накручивайте себя.',
      },
    ],
  },

  // ═══ БЫТ / ПОВСЕДНЕВНОЕ (daily) ═══
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'set',
    base_ru: 'устанавливать',
    forms: [
      {
        w: 'set up',
        m: 'настроить / организовать',
        ex: 'Set up your account first.',
        exRu: 'Сначала настройте свою учетную запись.',
      },
      {
        w: 'set off',
        m: 'отправиться',
        ex: 'We set off at 8 AM.',
        exRu: 'Мы отправились в путь в 8 утра.',
      },
      {
        w: 'set aside',
        m: 'отложить в сторону',
        ex: 'Set aside 20 min for reading.',
        exRu: 'Выделите 20 минут на чтение.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'fill',
    base_ru: 'заполнять',
    forms: [
      {
        w: 'fill in',
        m: 'заполнить (форму)',
        ex: 'Fill in the blanks.',
        exRu: 'Заполните пробелы.',
      },
      {
        w: 'fill out',
        m: 'заполнить полностью',
        ex: 'Fill out this form please.',
        exRu: 'Заполните эту форму, пожалуйста.',
      },
      {
        w: 'fill up',
        m: 'наполнить',
        ex: 'Fill up the glass.',
        exRu: 'Наполните стакан.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'clean',
    base_ru: 'убирать',
    forms: [
      {
        w: 'clean up',
        m: 'убраться',
        ex: 'Clean up your room.',
        exRu: 'Наведите порядок в своей комнате.',
      },
      {
        w: 'clean out',
        m: 'вычистить',
        ex: 'Clean out the fridge.',
        exRu: 'Очистите холодильник.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'use',
    base_ru: 'использовать',
    forms: [
      {
        w: 'use up',
        m: 'израсходовать',
        ex: 'We used up all the sugar.',
        exRu: 'Мы израсходовали весь сахар.',
      },
      {
        w: 'use to',
        m: 'раньше делал (do / did)',
        ex: 'I used to live in a village.',
        exRu: 'Раньше я жил в деревне.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'show',
    base_ru: 'показывать',
    forms: [
      {
        w: 'show up',
        m: 'появиться',
        ex: "He didn't show up.",
        exRu: 'Он не появился.',
      },
      {
        w: 'show off',
        m: 'хвастаться',
        ex: 'Stop showing off!',
        exRu: 'Хватит хвастаться!',
      },
      {
        w: 'show around',
        m: 'провести экскурсию',
        ex: 'Let me show you around.',
        exRu: 'Позвольте мне показать вам окрестности.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'end',
    base_ru: 'заканчиваться',
    forms: [
      {
        w: 'end up',
        m: 'в итоге оказаться',
        ex: 'We ended up in the wrong place.',
        exRu: 'Мы оказались не в том месте.',
      },
      {
        w: 'end up with',
        m: 'закончить с чем-то',
        ex: 'I ended up with a headache.',
        exRu: 'В итоге у меня заболела голова.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'keep',
    base_ru: 'держать / продолжать',
    forms: [
      {
        w: 'keep on',
        m: 'продолжать',
        ex: 'Keep on practicing!',
        exRu: 'Продолжайте практиковаться!',
      },
      {
        w: 'keep up',
        m: 'не отставать',
        ex: 'Keep up the good work!',
        exRu: 'Продолжайте в том же духе!',
      },
      {
        w: 'keep in touch',
        m: 'оставаться на связи',
        ex: "Let's keep in touch.",
        exRu: 'Давайте поддерживать связь.',
      },
      {
        w: 'keep away',
        m: 'держаться подальше',
        ex: 'Keep away from trouble.',
        exRu: 'Держитесь подальше от неприятностей.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'hang',
    base_ru: 'вешать / зависать',
    forms: [
      {
        w: 'hang on',
        m: 'подожди',
        ex: "Hang on, I'll be right back.",
        exRu: 'Подожди, я сейчас вернусь.',
      },
      {
        w: 'hang out',
        m: 'тусоваться',
        ex: "Let's hang out this weekend.",
        exRu: 'Давай пообщаемся на этих выходных.',
      },
      {
        w: 'hang up',
        m: 'повесить трубку',
        ex: 'She hung up without saying bye.',
        exRu: 'Она повесила трубку, не попрощавшись.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'figure',
    base_ru: 'фигура / понять',
    forms: [
      {
        w: 'figure out',
        m: 'разобраться',
        ex: "I can't figure out this grammar.",
        exRu: 'Я не могу разобраться в этой грамматике.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'point',
    base_ru: 'точка / указывать',
    forms: [
      {
        w: 'point out',
        m: 'указать на',
        ex: 'She pointed out my mistake.',
        exRu: 'Она указала на мою ошибку.',
      },
      {
        w: 'point at',
        m: 'показать пальцем',
        ex: "Don't point at people.",
        exRu: 'Не указывайте на людей.',
      },
    ],
  },

  // ═══ РЕЧЬ / РАЗГОВОР (talk) ═══
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'speak',
    base_ru: 'говорить',
    forms: [
      {
        w: 'speak up',
        m: 'говорить громче',
        ex: "Speak up, I can't hear you.",
        exRu: 'Говори, я тебя не слышу.',
      },
      {
        w: 'speak out',
        m: 'высказаться',
        ex: 'Speak out if you disagree.',
        exRu: 'Выскажитесь, если вы не согласны.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'bring up',
    base_ru: 'поднять тему',
    forms: [
      {
        w: 'bring up',
        m: 'упомянуть',
        ex: 'He brought up an interesting point.',
        exRu: 'Он поднял интересный момент.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'sum',
    base_ru: 'суммировать',
    forms: [
      {
        w: 'sum up',
        m: 'подвести итог',
        ex: 'Let me sum up the main points.',
        exRu: 'Подведу итог основным моментам.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'talk',
    base_ru: 'говорить',
    forms: [
      {
        w: 'talk into',
        m: 'уговорить',
        ex: 'She talked me into going.',
        exRu: 'Она уговорила меня пойти.',
      },
      {
        w: 'talk out of',
        m: 'отговорить',
        ex: 'I tried to talk him out of it.',
        exRu: 'Я пытался отговорить его от этого.',
      },
      {
        w: 'talk over',
        m: 'обсудить',
        ex: "Let's talk it over tonight.",
        exRu: 'Давай поговорим об этом сегодня вечером.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'agree',
    base_ru: 'соглашаться',
    forms: [
      {
        w: 'agree on',
        m: 'договориться о чём-то',
        ex: 'We agreed on a price.',
        exRu: 'Мы договорились о цене.',
      },
      {
        w: 'agree with',
        m: 'соглашаться с кем-то',
        ex: 'I agree with you.',
        exRu: 'Я согласен с вами.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'follow',
    base_ru: 'следовать',
    forms: [
      {
        w: 'follow up',
        m: 'уточнить / проследить',
        ex: "I'll follow up by email.",
        exRu: 'Я свяжусь с вами по электронной почте.',
      },
      {
        w: 'follow through',
        m: 'доводить до конца',
        ex: 'Follow through on your promise.',
        exRu: 'Выполните свое обещание.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'back',
    base_ru: 'назад / поддерживать',
    forms: [
      {
        w: 'back up',
        m: 'подкрепить / сохранить копию',
        ex: 'Back up your argument.',
        exRu: 'Подкрепите свой аргумент.',
      },
      {
        w: 'back down',
        m: 'отступить',
        ex: 'He backed down from the fight.',
        exRu: 'Он отказался от боя.',
      },
      {
        w: 'back out',
        m: 'отказаться',
        ex: 'She backed out of the deal.',
        exRu: 'Она отказалась от сделки.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'point',
    base_ru: 'смысл / указывать',
    forms: [
      {
        w: 'get the point',
        m: 'понять суть',
        ex: 'Did you get the point?',
        exRu: 'Вы поняли суть?',
      },
      {
        w: 'make a point',
        m: 'сделать замечание',
        ex: 'She made a good point.',
        exRu: 'Она высказала хорошее мнение.',
      },
    ],
  },

  // ═══ ДОПОЛНИТЕЛЬНЫЕ РАЗГОВОРНЫЕ ═══
  {
    cat: 'daily',
    type: 'word',
    base: 'actually',
    base_ru: 'на самом деле',
    ex: 'Actually, I changed my mind.',
    exRu: 'На самом деле, я передумал.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'basically',
    base_ru: 'в основном / короче',
    ex: "Basically, I don't agree.",
    exRu: 'В принципе, я не согласен.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'honestly',
    base_ru: 'честно говоря',
    ex: 'Honestly, I have no idea.',
    exRu: 'Честно говоря, понятия не имею.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'literally',
    base_ru: 'буквально',
    ex: "I literally can't stop laughing.",
    exRu: 'Я буквально не могу перестать смеяться.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'obviously',
    base_ru: 'очевидно',
    ex: "Obviously, that's wrong.",
    exRu: 'Очевидно, это неправильно.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'absolutely',
    base_ru: 'абсолютно / конечно',
    ex: "Absolutely! Let's do it.",
    exRu: 'Абсолютно! Давай сделаем это.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'apparently',
    base_ru: 'по всей видимости',
    ex: 'Apparently, he quit the job.',
    exRu: 'Судя по всему, он уволился с работы.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'somehow',
    base_ru: 'как-то / каким-то образом',
    ex: 'Somehow I forgot about it.',
    exRu: 'Как-то я об этом забыл.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'whatever',
    base_ru: 'что угодно / как хочешь',
    ex: 'Whatever you prefer is fine.',
    exRu: 'Что бы вы ни предпочли, это хорошо.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'anyway',
    base_ru: 'в любом случае',
    ex: "Anyway, let's move on.",
    exRu: 'В любом случае, давайте двигаться дальше.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'definitely',
    base_ru: 'определённо',
    ex: "I'll definitely be there.",
    exRu: 'Я обязательно буду там.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'exactly',
    base_ru: 'именно / точно',
    ex: "Exactly! That's what I mean.",
    exRu: 'Точно! Вот что я имею в виду.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'totally',
    base_ru: 'полностью / совсем',
    ex: 'I totally forgot about it.',
    exRu: 'Я совершенно забыл об этом.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'instead',
    base_ru: 'вместо',
    ex: "Let's walk instead of driving.",
    exRu: 'Давайте гулять, а не ехать.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'though',
    base_ru: 'хотя / хоть',
    ex: "It's cold. Nice day, though.",
    exRu: 'Холодно. Хороший день, однако.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'unless',
    base_ru: 'если только не',
    ex: "I won't go unless you come too.",
    exRu: 'Я не пойду, если ты тоже не придешь.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'once',
    base_ru: 'однажды / как только',
    ex: "Once you start, don't stop.",
    exRu: 'Начав, не останавливайтесь.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'since',
    base_ru: 'с тех пор как / так как',
    ex: "I've been here since Monday.",
    exRu: 'Я здесь с понедельника.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'meanwhile',
    base_ru: 'тем временем',
    ex: 'Meanwhile, she prepared dinner.',
    exRu: 'Тем временем она приготовила ужин.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'somehow',
    base_ru: 'почему-то',
    ex: "I somehow feel it'll be fine.",
    exRu: 'Я почему-то чувствую, что все будет хорошо.',
  },

  // ═══ РАСШИРЕНИЕ: B2–C1 разговор, дискурс, офис / жизнь ═══

  {
    cat: 'motion',
    type: 'phrasal',
    base: 'head',
    base_ru: 'направляться / возглавлять',
    forms: [
      {
        w: 'head for',
        m: 'направляться к',
        ex: "We're heading for the coast this weekend.",
        exRu: 'На этих выходных мы отправляемся на побережье.',
      },
      {
        w: 'head off',
        m: 'предотвратить / отправиться',
        ex: "Let's head off trouble before it spreads.",
        exRu: 'Давайте предотвратим беду, прежде чем она распространится.',
      },
      {
        w: 'head up',
        m: 'возглавлять',
        ex: 'She heads up the design team.',
        exRu: 'Она возглавляет команду дизайнеров.',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'carry',
    base_ru: 'нести / продолжать',
    forms: [
      {
        w: 'carry on',
        m: 'продолжать (несмотря ни на что)',
        ex: "Carry on talking — I won't interrupt.",
        exRu: 'Продолжайте говорить — я не перебиваю.',
      },
      {
        w: 'carry out',
        m: 'выполнить / провести',
        ex: 'We need to carry out a full audit.',
        exRu: 'Нам необходимо провести полную проверку.',
      },
      {
        w: 'carry over',
        m: 'перенести / остаться',
        ex: "Let's carry this discussion over to Monday.",
        exRu: 'Давайте перенесем это обсуждение на понедельник.',
      },
      {
        w: 'carry through',
        m: 'довести до конца',
        ex: 'She carried the project through despite delays.',
        exRu: 'Она осуществила проект, несмотря на задержки.',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'pass',
    base_ru: 'проходить / передавать',
    forms: [
      {
        w: 'pass away',
        m: 'скончаться (эвф.)',
        ex: 'Her grandfather passed away last winter.',
        exRu: 'Прошлой зимой умер ее дедушка.',
      },
      {
        w: 'pass out',
        m: 'потерять сознание / раздать',
        ex: 'Two runners passed out in the heat.',
        exRu: 'Двое бегунов потеряли сознание от жары.',
      },
      {
        w: 'pass up',
        m: 'упустить возможность',
        ex: "Don't pass up a chance to practise with natives.",
        exRu: 'Не упускайте возможности попрактиковаться с носителями языка.',
      },
      {
        w: 'pass for',
        m: 'сойти за',
        ex: 'That accent could pass for British in a noisy bar.',
        exRu: 'В шумном баре этот акцент мог бы сойти за британский.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'pay',
    base_ru: 'платить',
    forms: [
      {
        w: 'pay off',
        m: 'окупиться / выплатить долг',
        ex: 'Years of study finally paid off.',
        exRu: 'Годы учебы наконец принесли свои плоды.',
      },
      {
        w: 'pay back',
        m: 'отплатить / вернуть деньги',
        ex: "I'll pay you back next week, I promise.",
        exRu: 'Я верну тебе деньги на следующей неделе, обещаю.',
      },
      {
        w: 'pay for',
        m: 'расплатиться (последствиями)',
        ex: "You'll pay for that careless remark.",
        exRu: 'Вы заплатите за это неосторожное замечание.',
      },
      {
        w: 'pay up',
        m: 'расплатиться полностью',
        ex: 'He refused to pay up until he saw a receipt.',
        exRu: 'Он отказался платить, пока не увидел чек.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'lay',
    base_ru: 'класть / увольнять',
    forms: [
      {
        w: 'lay off',
        m: 'уволить / оставить в покое',
        ex: 'The factory laid off two hundred workers.',
        exRu: 'Завод уволил двести рабочих.',
      },
      {
        w: 'lay out',
        m: 'разложить / спланировать',
        ex: 'She laid out the budget in clear charts.',
        exRu: 'Она изложила бюджет в четких диаграммах.',
      },
      {
        w: 'lay into',
        m: 'наброситься с критикой',
        ex: 'The press laid into the minister after the leak.',
        exRu: 'Пресса обрушилась на министра после утечки.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'miss',
    base_ru: 'пропускать',
    forms: [
      {
        w: 'miss out on',
        m: 'упустить (возможность)',
        ex: "Don't miss out on the early-bird discount.",
        exRu: 'Не упустите скидку раннего бронирования.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'brush',
    base_ru: 'чистить / слегка коснуться',
    forms: [
      {
        w: 'brush up on',
        m: 'освежить (навык)',
        ex: 'I need to brush up on my presentation skills.',
        exRu: 'Мне нужно освежить свои навыки презентации.',
      },
      {
        w: 'brush off',
        m: 'отмахнуться',
        ex: 'He brushed off every criticism as jealousy.',
        exRu: 'Он отмахивался от любой критики как от зависти.',
      },
      {
        w: 'brush aside',
        m: 'отодвинуть / проигнорировать',
        ex: 'They brushed aside all ethical concerns.',
        exRu: 'Они отмахнулись от всех этических проблем.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'rule',
    base_ru: 'правило / исключать',
    forms: [
      {
        w: 'rule out',
        m: 'исключить (версию)',
        ex: 'Police ruled out suicide early in the case.',
        exRu: 'Полиция на раннем этапе дела исключила самоубийство.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'phase',
    base_ru: 'фаза / постепенно убрать',
    forms: [
      {
        w: 'phase out',
        m: 'постепенно свернуть',
        ex: 'The company is phasing out single-use plastics.',
        exRu: 'Компания постепенно отказывается от одноразового пластика.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'spell',
    base_ru: 'произносить по буквам',
    forms: [
      {
        w: 'spell out',
        m: 'разжевать / объяснить досконально',
        ex: 'Let me spell out what this clause means.',
        exRu: 'Позвольте мне объяснить, что означает этот пункт.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'flesh',
    base_ru: 'плоть / детализировать',
    forms: [
      {
        w: 'flesh out',
        m: 'детализировать / обрасти деталями',
        ex: 'Can you flesh out the second paragraph?',
        exRu: 'Можете ли вы конкретизировать второй абзац?',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'weigh',
    base_ru: 'взвешивать',
    forms: [
      {
        w: 'weigh in',
        m: 'высказаться / взвеситься',
        ex: 'Experts weighed in on both sides of the debate.',
        exRu: 'Эксперты высказались по обеим сторонам дискуссии.',
      },
      {
        w: 'weigh up',
        m: 'оценить за и против',
        ex: "We're weighing up two equally strong candidates.",
        exRu: 'Мы взвешиваем двух одинаково сильных кандидатов.',
      },
    ],
  },
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'single',
    base_ru: 'один / выделить',
    forms: [
      {
        w: 'single out',
        m: 'выделить (часто негативно)',
        ex: 'Why was I singled out for extra homework?',
        exRu: 'Почему мне выделили дополнительную домашнюю работу?',
      },
    ],
  },
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'play',
    base_ru: 'играть / преуменьшить',
    forms: [
      {
        w: 'play down',
        m: 'приуменьшить',
        ex: 'The CEO played down rumours of a merger.',
        exRu: 'Генеральный директор преуменьшил слухи о слиянии.',
      },
      {
        w: 'play up',
        m: 'подчеркнуть / капризничать',
        ex: 'The injury played up again in the second half.',
        exRu: 'Травма снова обострилась во втором тайме.',
      },
      {
        w: 'play along',
        m: 'подыграть / притвориться',
        ex: 'I played along until I understood the scam.',
        exRu: 'Я подыгрывал, пока не понял суть мошенничества.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'map',
    base_ru: 'карта / спланировать',
    forms: [
      {
        w: 'map out',
        m: 'детально спланировать',
        ex: 'They mapped out a five-year career path.',
        exRu: 'Они наметили пятилетний карьерный путь.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'iron',
    base_ru: 'утюг / сгладить',
    forms: [
      {
        w: 'iron out',
        m: 'сгладить (проблемы)',
        ex: 'We still need to iron out a few legal details.',
        exRu: 'Нам еще нужно согласовать некоторые юридические детали.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'shore',
    base_ru: 'берег / подкрепить',
    forms: [
      {
        w: 'shore up',
        m: 'подкрепить / укрепить',
        ex: 'The bank shored up reserves before the crisis.',
        exRu: 'Банк укрепил резервы еще до кризиса.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'rope',
    base_ru: 'верёвка / втянуть',
    forms: [
      {
        w: 'rope in',
        m: 'втянуть / заручиться помощью',
        ex: 'They roped me in to organise the whole event.',
        exRu: 'Они привлекли меня к организации всего мероприятия.',
      },
    ],
  },
  {
    cat: 'motion',
    type: 'phrasal',
    base: 'veer',
    base_ru: 'резко свернуть',
    forms: [
      {
        w: 'veer off',
        m: 'свернуть с темы / курса',
        ex: 'The conversation veered off into politics.',
        exRu: 'Разговор перешел на политику.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'cash',
    base_ru: 'наличные',
    forms: [
      {
        w: 'cash in on',
        m: 'нажиться на',
        ex: 'Influencers always try to cash in on trends.',
        exRu: 'Влиятельные люди всегда стараются нажиться на тенденциях.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'touch',
    base_ru: 'касаться',
    forms: [
      {
        w: 'touch on',
        m: 'слегка затронуть тему',
        ex: 'The lecture only touched on phonetics at the end.',
        exRu: 'В конце лекции речь шла только о фонетике.',
      },
      {
        w: 'touch base',
        m: 'коротко связаться',
        ex: "Let's touch base after the client call.",
        exRu: 'Давайте коснемся базы после звонка клиента.',
      },
    ],
  },
  {
    cat: 'daily',
    type: 'phrasal',
    base: 'stock',
    base_ru: 'запас / снабдить',
    forms: [
      {
        w: 'stock up on',
        m: 'закупиться запасом',
        ex: 'We stocked up on water before the storm.',
        exRu: 'Мы запаслись водой перед грозой.',
      },
    ],
  },
  {
    cat: 'emotion',
    type: 'phrasal',
    base: 'freak',
    base_ru: 'испуг / паника',
    forms: [
      {
        w: 'freak out',
        m: 'паниковать / прийти в восторг',
        ex: "Don't freak out — we can fix this bug.",
        exRu: 'Не волнуйтесь — мы можем исправить эту ошибку.',
      },
    ],
  },
  {
    cat: 'relation',
    type: 'phrasal',
    base: 'count',
    base_ru: 'считать / полагаться',
    forms: [
      {
        w: 'count on',
        m: 'положиться на',
        ex: 'You can count on me to proofread the deck.',
        exRu: 'Вы можете рассчитывать на то, что я вычитаю колоду.',
      },
      {
        w: 'count in',
        m: 'включить в планы',
        ex: "If there's pizza, count me in.",
        exRu: 'Если будет пицца, запишите меня.',
      },
      {
        w: 'count out',
        m: 'не включать',
        ex: "If it's a hike, count me out — my knee hurts.",
        exRu: 'Если это поход, меня можно исключить — у меня болит колено.',
      },
    ],
  },
  {
    cat: 'object',
    type: 'phrasal',
    base: 'swap',
    base_ru: 'обменять',
    forms: [
      {
        w: 'swap out',
        m: 'заменить (деталь)',
        ex: 'We swapped out the old router for a mesh system.',
        exRu: 'Мы заменили старый роутер на ячеистую систему.',
      },
    ],
  },
  {
    cat: 'talk',
    type: 'phrasal',
    base: 'chime',
    base_ru: 'перезвон / вставить слово',
    forms: [
      {
        w: 'chime in',
        m: 'вставить замечание',
        ex: 'Everyone chimed in with a different opinion.',
        exRu: 'Все высказали разное мнение.',
      },
    ],
  },

  {
    cat: 'talk',
    type: 'word',
    base: 'arguably',
    base_ru: 'можно утверждать / по общему мнению',
    ex: 'She is arguably the best speaker in the cohort.',
    exRu: 'Она, пожалуй, лучший оратор в когорте.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'admittedly',
    base_ru: 'признаться / по правде',
    ex: 'Admittedly, I skipped the listening homework last week.',
    exRu: 'Признаюсь, на прошлой неделе я пропустил домашнее задание по аудированию.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'presumably',
    base_ru: 'предположительно',
    ex: 'Presumably, the meeting will run over if QA joins.',
    exRu: 'Предположительно, встреча будет перенесена, если к ней присоединится QA.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'granted',
    base_ru: 'справедливо / допустим (уступка)',
    ex: 'Granted, the course is hard, but the payoff is huge.',
    exRu: 'Конечно, курс трудный, но отдача огромна.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'conversely',
    base_ru: 'наоборот (логическая связка)',
    ex: 'The north loves snow; conversely, the south dreads it.',
    exRu: 'Север любит снег; и наоборот, юг боится этого.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'likewise',
    base_ru: 'взаимно / также',
    ex: 'Pleased to meet you — Likewise.',
    exRu: 'Рад знакомству — Тоже самое.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'hence',
    base_ru: 'отсюда / поэтому (форм.)',
    ex: 'The data was noisy; hence the wide confidence interval.',
    exRu: 'Данные были зашумлены; отсюда и широкий доверительный интервал.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'thus',
    base_ru: 'таким образом / следовательно',
    ex: 'Costs rose; thus we froze hiring for Q3.',
    exRu: 'Затраты выросли; поэтому мы заморозили прием на работу в третьем квартале.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'whereby',
    base_ru: 'посредством чего / в силу чего',
    ex: 'We need a process whereby errors surface before release.',
    exRu: 'Нам нужен процесс, при котором ошибки выявляются перед выпуском.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'albeit',
    base_ru: 'хотя / пусть даже',
    ex: 'The fix works, albeit with a ten-percent performance hit.',
    exRu: 'Исправление работает, хотя и с десятипроцентным снижением производительности.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'pending',
    base_ru: 'в ожидании / до выяснения',
    ex: "Your visa is still pending — don't book flights yet.",
    exRu: 'Ваша виза все еще находится на рассмотрении — пока не бронируйте авиабилеты.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'accordingly',
    base_ru: 'соответственно',
    ex: 'The spec changed; we updated the tests accordingly.',
    exRu: 'Спецификация изменилась; мы соответствующим образом обновили тесты.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'namely',
    base_ru: 'а именно',
    ex: 'One blocker remains, namely access to the staging API.',
    exRu: 'Остается один блокировщик, а именно доступ к промежуточному API.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'notably',
    base_ru: 'в частности / заметно',
    ex: 'Several bugs were fixed, notably the memory leak.',
    exRu: 'Исправлено несколько ошибок, в частности утечка памяти.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'respectively',
    base_ru: 'соответственно (по порядку)',
    ex: 'Alice and Bob scored 89 and 92, respectively.',
    exRu: 'Алиса и Боб набрали 89 и 92 балла соответственно.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'roughly',
    base_ru: 'примерно / грубо',
    ex: 'Roughly half the class finished before the bell.',
    exRu: 'Примерно половина класса закончила занятия до звонка.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'ballpark',
    base_ru: 'приблизительный порядок (разг.)',
    ex: 'Give me a ballpark figure for the migration cost.',
    exRu: 'Назовите мне примерную стоимость миграции.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'offhand',
    base_ru: 'навскидку / без подготовки',
    ex: "Offhand, I'd say we need two more sprints.",
    exRu: 'Навскидку, я бы сказал, что нам нужно еще два спринта.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'by and large',
    base_ru: 'в целом / в общем',
    ex: 'By and large, the rollout was smoother than expected.',
    exRu: 'В целом внедрение прошло более гладко, чем ожидалось.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'for the most part',
    base_ru: 'в основном',
    ex: 'For the most part, students prefer shorter feedback loops.',
    exRu: 'По большей части студенты предпочитают более короткие циклы обратной связи.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'as far as I can tell',
    base_ru: 'насколько я могу судить',
    ex: 'As far as I can tell, the accent is Canadian, not US.',
    exRu: 'Насколько я могу судить, акцент канадский, а не американский.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: "as far as I'm concerned",
    base_ru: 'что касается меня',
    ex: "As far as I'm concerned, the deadline is non-negotiable.",
    exRu: 'Насколько я понимаю, сроки не подлежат обсуждению.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'fair enough',
    base_ru: 'справедливо / ладно, согласен',
    ex: 'You need a break — fair enough, we can rehearse tomorrow.',
    exRu: 'Тебе нужен перерыв — честно, мы можем порепетировать завтра.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'no wonder',
    base_ru: 'неудивительно',
    ex: "No wonder you're tired — you've been coding since dawn.",
    exRu: 'Неудивительно, что ты устал — ты программировал с самого рассвета.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'small wonder',
    base_ru: 'совсем неудивительно',
    ex: 'Small wonder the app crashed; we never load-tested it.',
    exRu: 'Неудивительно, что приложение вышло из строя; мы никогда не тестировали его под нагрузкой.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'come to think of it',
    base_ru: 'если подумать / кстати',
    ex: 'Come to think of it, we already covered that tense.',
    exRu: 'Если подумать, мы уже рассмотрели это время.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'now that you mention it',
    base_ru: 'раз уж зашла речь',
    ex: 'Now that you mention it, the audio did sound clipped.',
    exRu: 'Теперь, когда вы упомянули об этом, звук действительно был обрезан.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'on second thought',
    base_ru: 'если подумать ещё раз',
    ex: "On second thought, let's postpone the mock interview.",
    exRu: 'А вообще, давайте отложим шуточное интервью.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'all things considered',
    base_ru: 'если учесть всё',
    ex: 'All things considered, your progress this month is solid.',
    exRu: 'Учитывая все обстоятельства, ваш прогресс в этом месяце солидный.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'at the end of the day',
    base_ru: 'в конечном счёте',
    ex: 'At the end of the day, fluency beats perfect grammar.',
    exRu: 'В конце концов, беглость речи превосходит идеальную грамматику.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'when it comes to',
    base_ru: 'когда речь о / что касается',
    ex: 'When it comes to phrasals, context is everything.',
    exRu: 'Когда дело доходит до фраз, контекст решает все.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'speaking of which',
    base_ru: 'кстати об этом',
    ex: 'Speaking of which, did you register for the exam?',
    exRu: 'Кстати, ты записался на экзамен?',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'that said',
    base_ru: 'при этом / однако',
    ex: 'The hotel was cheap; that said, the Wi-Fi was unusable.',
    exRu: 'Отель был дешевым; тем не менее, Wi-Fi был непригоден для использования.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'having said that',
    base_ru: 'сказав это / тем не менее',
    ex: "Having said that, I still wouldn't skip shadowing practice.",
    exRu: 'Сказав это, я бы все равно не пропустил практику слежки.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'on the whole',
    base_ru: 'в целом',
    ex: 'On the whole, the feedback from tutors was positive.',
    exRu: 'В целом отзывы репетиторов были положительными.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'by the same token',
    base_ru: 'с другой стороны / аналогично',
    ex: 'Prices fell; by the same token, quality dipped.',
    exRu: 'Цены упали; по той же причине качество упало.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: "for what it's worth",
    base_ru: 'на всякий случай (мнение)',
    ex: "For what it's worth, I'd rewrite the opening line.",
    exRu: 'Чего бы это ни стоило, я бы переписал вступительную строку.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'touch wood',
    base_ru: 'тьфу-тьфу (UK)',
    ex: "I haven't caught flu yet — touch wood.",
    exRu: 'Я еще не заразился гриппом — потрогай дерево.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'fingers crossed',
    base_ru: 'скрестим пальцы',
    ex: 'Fingers crossed the visa arrives before the course starts.',
    exRu: 'Скрестим пальцы, виза прибудет до начала курса.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'on the same page',
    base_ru: 'понимать друг друга одинаково',
    ex: "Let's align so we're on the same page about deliverables.",
    exRu: 'Давайте договоримся, чтобы мы были на одной волне в отношении результатов.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'see eye to eye',
    base_ru: 'полностью соглашаться',
    ex: "We don't always see eye to eye on methodology.",
    exRu: 'Мы не всегда сходимся во взглядах на методологию.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'give someone the benefit of the doubt',
    base_ru: 'поверить на слово',
    ex: "I'll give you the benefit of the doubt this once.",
    exRu: 'На этот раз я дам вам презумпцию невиновности.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'burn bridges',
    base_ru: 'спалить мосты',
    ex: 'Quitting by email only will burn bridges with HR.',
    exRu: 'Уход только по электронной почте сожжет мосты с отделом кадров.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'pull strings',
    base_ru: 'дёрнуть за ниточки (влияние)',
    ex: 'He pulled strings to get a last-minute test slot.',
    exRu: 'Он потянул за веревочки, чтобы получить место для теста в последнюю минуту.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'ahead of schedule',
    base_ru: 'раньше срока',
    ex: "We're slightly ahead of schedule on the vocabulary deck.",
    exRu: 'Мы немного опережаем график по словарному запасу.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'behind schedule',
    base_ru: 'с отставанием от графика',
    ex: "We're two modules behind schedule — block extra time.",
    exRu: 'Мы отстаем от графика на два модуля — заблокируйте дополнительное время.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'under pressure',
    base_ru: 'под давлением',
    ex: 'She speaks clearly even under pressure.',
    exRu: 'Она говорит ясно даже под давлением.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'on edge',
    base_ru: 'на взводе',
    ex: 'Everyone was on edge before the results dropped.',
    exRu: 'Все были на грани, прежде чем результаты упали.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'at ease',
    base_ru: 'расслабленно / непринуждённо',
    ex: 'Small talk helps me feel at ease before interviews.',
    exRu: 'Светская беседа помогает мне чувствовать себя непринужденно перед собеседованием.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'mixed feelings',
    base_ru: 'смешанные чувства',
    ex: 'I have mixed feelings about skipping the immersion week.',
    exRu: 'У меня смешанные чувства по поводу пропуска недели погружения.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'gut feeling',
    base_ru: 'интуиция / чутьё',
    ex: 'My gut feeling is that this idiom list is still too short.',
    exRu: 'Я чувствую, что этот список идиом все еще слишком короток.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'food for thought',
    base_ru: 'пища для размышлений',
    ex: 'That podcast gave me real food for thought on accents.',
    exRu: 'Этот подкаст дал мне настоящую пищу для размышлений об акцентах.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'read between the lines',
    base_ru: 'читать между строк',
    ex: "Read between the lines — they're not renewing the contract.",
    exRu: 'Читайте между строк — они не продлевают контракт.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'read the room',
    base_ru: 'понять настроение присутствующих',
    ex: 'Learn to read the room before cracking sarcastic jokes.',
    exRu: 'Научитесь читать комнату, прежде чем отпускать саркастические шутки.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'silver lining',
    base_ru: 'просвет / лучик надежды',
    ex: 'Missing the flight had a silver lining: I finished the essay.',
    exRu: 'У опоздания на рейс была положительная сторона: я закончил эссе.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'learning curve',
    base_ru: 'кривая обучения',
    ex: "There's a steep learning curve with legal English.",
    exRu: 'Обучение юридическому английскому требует крутых моментов.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'deep dive',
    base_ru: 'глубокое погружение (жарг.)',
    ex: "We'll do a deep dive into linking sounds next lesson.",
    exRu: 'На следующем уроке мы углубимся в связывание звуков.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'quick win',
    base_ru: 'быстрый результат (жарг.)',
    ex: 'Flashcards are a quick win for spaced repetition.',
    exRu: 'Карточки — это быстрая победа в интервальном повторении.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'pain point',
    base_ru: 'болевая точка / проблема',
    ex: 'Pronunciation is the main pain point for most learners.',
    exRu: 'Произношение является основной проблемой для большинства учащихся.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'raise the bar',
    base_ru: 'поднять планку',
    ex: 'This new textbook really raises the bar for self-study.',
    exRu: 'Этот новый учебник действительно поднимает планку самостоятельного обучения.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'move the needle',
    base_ru: 'сдвинуть ситуацию (заметно)',
    ex: "Ten minutes a day won't move the needle unless it's daily.",
    exRu: 'Десять минут в день не сдвинут стрелку, если только они не будут ежедневными.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'low-hanging fruit',
    base_ru: 'лёгкая добыча / простые победы',
    ex: "Fix typos first — that's low-hanging fruit.",
    exRu: 'Сначала исправьте опечатки — это легко висит.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'circle back',
    base_ru: 'вернуться к теме позже (офис)',
    ex: "Let's circle back after we've seen the rubric.",
    exRu: 'Давайте вернемся назад после того, как мы увидели рубрику.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'loop someone in',
    base_ru: 'включить в переписку / в курс',
    ex: 'Loop the tutor in so they see the draft thesis.',
    exRu: 'Подключите преподавателя, чтобы он увидел черновик диссертации.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'take something with a grain of salt',
    base_ru: 'относиться скептически',
    ex: 'Take viral grammar hacks with a grain of salt.',
    exRu: 'Относитесь к вирусным грамматическим хакам с недоверием.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'on the fence',
    base_ru: 'в нерешительности',
    ex: "I'm still on the fence about switching exam boards.",
    exRu: 'Я все еще подумываю о смене экзаменационной комиссии.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'worth a shot',
    base_ru: 'стоит попробовать',
    ex: 'Recording yourself is awkward, but worth a shot.',
    exRu: 'Записывать себя неудобно, но стоит попробовать.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'long story short',
    base_ru: 'короче говоря',
    ex: 'Long story short, we missed the registration window.',
    exRu: 'Короче говоря, мы пропустили окно регистрации.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'to make a long story short',
    base_ru: 'чтобы не распинаться',
    ex: 'To make a long story short, I chose the wrong tense.',
    exRu: 'Короче говоря, я выбрал неправильное время.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: "can't help but",
    base_ru: 'не могу не (сильное чувство)',
    ex: "I can't help but compare my accent to the reference track.",
    exRu: 'Я не могу не сравнить свой акцент с эталонным треком.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'be dying to',
    base_ru: 'очень хотеть (разг.)',
    ex: "I'm dying to hear how your panel interview went.",
    exRu: 'Мне не терпится услышать, как прошло твое групповое собеседование.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'be sick of',
    base_ru: 'сыт по горло',
    ex: "I'm sick of drilling minimal pairs without context.",
    exRu: 'Мне надоело сверлить минимальные пары без контекста.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'be thrilled to bits',
    base_ru: 'в восторге до небес (UK)',
    ex: 'She was thrilled to bits about the scholarship.',
    exRu: 'Она была в восторге от стипендии.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: "get on someone's nerves",
    base_ru: 'действовать на нервы',
    ex: 'That notification sound gets on my nerves.',
    exRu: 'Этот звук уведомления действует мне на нервы.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'give someone a hard time',
    base_ru: 'доставать / подкалывать',
    ex: 'My friends gave me a hard time about my old-fashioned slang.',
    exRu: 'Мои друзья не давали мне покоя из-за моего старомодного сленга.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'cut someone some slack',
    base_ru: 'проявить снисхождение',
    ex: 'Cut yourself some slack — week one is always chaotic.',
    exRu: 'Будьте немного послабее — первая неделя всегда хаотична.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: "have someone's back",
    base_ru: 'прикрыть спину',
    ex: 'Thanks for having my back during the oral exam.',
    exRu: 'Спасибо, что поддержали меня во время устного экзамена.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'throw someone under the bus',
    base_ru: 'подставить / сдать',
    ex: 'He threw his teammate under the bus in the review meeting.',
    exRu: 'На обзорной встрече он бросил своего товарища по команде под автобус.',
  },
  {
    cat: 'motion',
    type: 'word',
    base: 'go the extra mile',
    base_ru: 'положить душу / сделать больше нужного',
    ex: 'She went the extra mile annotating every transcript.',
    exRu: 'Она приложила все усилия, комментируя каждую стенограмму.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'call it a day',
    base_ru: 'закончить на сегодня',
    ex: "We've covered twelve chunks — let's call it a day.",
    exRu: 'Мы рассмотрели двенадцать частей — на этом закончим.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'call it a night',
    base_ru: 'разойтись спать',
    ex: "My brain is fried — let's call it a night.",
    exRu: 'Мой мозг поджарился — назовем это ночью.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'burn the midnight oil',
    base_ru: 'работать допоздна',
    ex: 'I burned the midnight oil polishing the slides.',
    exRu: 'Я сжигал полночь масло, полируя слайды.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'crunch time',
    base_ru: 'жаркое время / дедлайны',
    ex: "It's crunch time — mock tests start Monday.",
    exRu: 'Настало решающее время — пробные тесты начнутся в понедельник.',
  },
  {
    cat: 'object',
    type: 'word',
    base: "dot the i's and cross the t's",
    base_ru: 'проверить до мелочей',
    ex: "Before you submit, dot the i's and cross the t's.",
    exRu: 'Прежде чем отправить сообщение, расставьте все точки над «i» и зачеркните «t».',
  },
  {
    cat: 'object',
    type: 'word',
    base: 'get the hang of',
    base_ru: 'освоить / набить руку',
    ex: "You'll get the hang of weak forms after enough listening.",
    exRu: 'После достаточного прослушивания вы освоите слабые формы.',
  },
  {
    cat: 'object',
    type: 'word',
    base: 'get out of hand',
    base_ru: 'выйти из-под контроля',
    ex: 'The debate got out of hand once politics appeared.',
    exRu: 'Дебаты вышли из-под контроля, как только появилась политика.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'beat around the bush',
    base_ru: 'ходить вокруг да около',
    ex: 'Stop beating around the bush — did I pass?',
    exRu: 'Хватит ходить вокруг да около — я прошел?',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'get straight to the point',
    base_ru: 'сразу перейти к делу',
    ex: "I'll get straight to the point: your thesis needs a hook.",
    exRu: 'Перейду сразу к делу: вашей диссертации нужна зацепка.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'talk shop',
    base_ru: 'обсуждать работу (не в рабочее время)',
    ex: 'Engineers love to talk shop even at parties.',
    exRu: 'Инженеры любят поговорить о делах даже на вечеринках.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'talk past each other',
    base_ru: 'говорить мимо друг друга',
    ex: "We talked past each other until we defined 'fluency'.",
    exRu: 'Мы говорили мимо друг друга, пока не определили «беглость».',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'keep a straight face',
    base_ru: 'не рассмеяться / сохранять серьёзность',
    ex: "I couldn't keep a straight face at his malapropism.",
    exRu: 'Я не мог сохранять серьезное лицо из-за его неправильного подхода.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'burst out laughing',
    base_ru: 'расхохотаться',
    ex: 'She burst out laughing at the unintentional pun.',
    exRu: 'Она рассмеялась над непреднамеренным каламбуром.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'be on cloud nine',
    base_ru: 'на седьмом небе',
    ex: 'After the pass grade, he was on cloud nine.',
    exRu: 'После проходного балла он был на седьмом небе от счастья.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: "have butterflies in one's stomach",
    base_ru: '«бабочки» в животе',
    ex: 'I always have butterflies before speaking slots.',
    exRu: 'У меня всегда есть бабочки перед разговорными слотами.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'hit the sack',
    base_ru: 'лечь спать (разг.)',
    ex: "I'm going to hit the sack — we resume at eight.",
    exRu: 'Я собираюсь уйти — мы продолжим в восемь.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'hit the books',
    base_ru: 'засесть за учёбу',
    ex: 'Exam week means hitting the books every evening.',
    exRu: 'Экзаменационная неделя означает, что нужно заниматься учебниками каждый вечер.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'run errands',
    base_ru: 'решать бытовые дела',
    ex: "I'll run errands after class, then join the study group.",
    exRu: 'После уроков я побегу по делам, а затем присоединюсь к учебной группе.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'kill time',
    base_ru: 'убить время',
    ex: 'We killed time in the café waiting for the results.',
    exRu: 'Мы убили время в кафе в ожидании результатов.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'save the day',
    base_ru: 'спасти ситуацию',
    ex: 'Your backup recording saved the day when the mic died.',
    exRu: 'Ваша резервная запись сохранила тот день, когда сломался микрофон.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'spell disaster',
    base_ru: 'означать катастрофу',
    ex: 'Skipping sleep before the oral would spell disaster.',
    exRu: 'Пропуск сна до орального приема приведет к катастрофе.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'a blessing in disguise',
    base_ru: 'замаскированная удача',
    ex: 'Failing that module was a blessing in disguise — I relearned basics.',
    exRu: 'Неудача с этим модулем была замаскированным благословением — я заново изучил основы.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'the last straw',
    base_ru: 'последняя капля',
    ex: 'Losing audio during the mock was the last straw.',
    exRu: 'Потеря звука во время имитации стала последней каплей.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'add insult to injury',
    base_ru: 'солить рану',
    ex: 'To add insult to injury, the feedback arrived at 3 a.m.',
    exRu: 'В довершение всего, ответ пришел в 3 часа ночи.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'patch things up',
    base_ru: 'помириться / залатать отношения',
    ex: 'We patched things up after the tense group project.',
    exRu: 'Мы наладили отношения после напряженного группового проекта.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'clear the air',
    base_ru: 'прояснить обстановку',
    ex: 'A short walk helped us clear the air after the argument.',
    exRu: 'Короткая прогулка помогла нам прояснить ситуацию после ссоры.',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'give someone the cold shoulder',
    base_ru: 'оказать холодок',
    ex: 'Why is she giving me the cold shoulder in class chats?',
    exRu: 'Почему она холодно относится ко мне в классных чатах?',
  },
  {
    cat: 'relation',
    type: 'word',
    base: 'on good terms',
    base_ru: 'в хороших отношениях',
    ex: "We're on good terms even though we disagreed sharply.",
    exRu: 'Мы в хороших отношениях, хотя резко расходимся во мнениях.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'for the record',
    base_ru: 'для протокола / на будущее',
    ex: 'For the record, I disagree with dropping shadowing.',
    exRu: 'Для справки: я не согласен с отказом от слежки.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'off the record',
    base_ru: 'не для печати / неофициально',
    ex: 'Off the record, that examiner loves colloquial fillers.',
    exRu: 'Не для протокола, этот экзаменатор любит разговорные наполнители.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'in a nutshell',
    base_ru: 'в двух словах',
    ex: 'In a nutshell, your intonation carries more weight than r.',
    exRu: 'Короче говоря, ваша интонация имеет больший вес, чем r.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'needless to say',
    base_ru: 'само собой разумеется',
    ex: 'Needless to say, consistency beats occasional cramming.',
    exRu: 'Излишне говорить, что последовательность лучше случайной зубрежки.',
  },
  {
    cat: 'talk',
    type: 'word',
    base: 'come in handy',
    base_ru: 'пригодиться',
    ex: 'Those filler phrases will come in handy during Q&A.',
    exRu: 'Эти фразы-вставки пригодятся во время вопросов и ответов.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'rule of thumb',
    base_ru: 'практическое правило / эвристика',
    ex: 'As a rule of thumb, shadow ten minutes for every hour of input.',
    exRu: 'Как правило, на каждый час ввода следует выделять десять минут.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: "the lion's share",
    base_ru: 'львиная доля',
    ex: "Listening took the lion's share of my study time.",
    exRu: 'Прослушивание занимало львиную долю моего учебного времени.',
  },
  {
    cat: 'daily',
    type: 'word',
    base: 'a drop in the ocean',
    base_ru: 'капля в море',
    ex: 'One list is a drop in the ocean — keep curating your own.',
    exRu: 'Один список — это капля в море — продолжайте составлять свой собственный.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: "keep one's chin up",
    base_ru: 'не вешать нос',
    ex: 'Keep your chin up — plateaus are normal in January.',
    exRu: 'Держите подбородок высоко — плато в январе — это нормально.',
  },
  {
    cat: 'emotion',
    type: 'word',
    base: 'take it to heart',
    base_ru: 'принять близко к сердцу',
    ex: "Don't take every red mark to heart; focus on patterns.",
    exRu: 'Не принимайте близко к сердцу каждую красную отметку; сосредоточьтесь на шаблонах.',
  },
];
