export const TAG_NAMES = {
  about: 'о себе',
  question: 'вопросы/связки',
  action: 'действия',
  time: 'время',
  feeling: 'эмоции',
  number: 'место/число',
  dev: 'developer',
  general: 'общее',
  personality: 'характер',
  business: 'бизнес',
  education: 'образование',
  communication: 'общение',
  health: 'здоровье',
  work: 'работа',
  nature: 'природа',
  home: 'дом',
  travel: 'путешествия',
  shopping: 'покупки',
  food: 'еда',
  tech: 'технологии',
  science: 'наука',
  politics: 'политика',
  law: 'право',
  emotions: 'эмоции',
  entertainment: 'развлечения',
  games: 'игры',
  weather: 'погода',
  morality: 'мораль',
  architecture: 'архитектура',
  adverb: 'наречия',
};

export const ALLOWED_CATS = Object.keys(TAG_NAMES);
